[package]
name = "synos-webterm"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[lib]
path = "src/lib.rs"

[dependencies]
synos-protocol = { path = "../protocol" }
syn-shell = { path = "../syn-shell" }
synos-ipc = { path = "../ipc" }
synos-service-scale = { path = "../service-scale" }

[dev-dependencies]
synos-status = { path = "../status" }
