/* Generated by tools/generate_c_abi.py. Edit abi/ghostos-abi.toml. */
#ifndef GHOSTOS_ABI_H
#define GHOSTOS_ABI_H
#include <stddef.h>
#include <stdbool.h>
#include <stdint.h>
#include "ghostos/status.h"

#define GHOSTOS_ABI_SCHEMA_VERSION 1u
#define GHOSTOS_ABI_REVISION 15u
#define GHOSTOS_RPC_PROTOCOL_VERSION 1u
#define GHOSTOS_RPC_FRAME_HEADER_BYTES 24u
#define GHOSTOS_RPC_MAX_FRAME_BYTES 4096u
#define GHOSTOS_RPC_CAPABILITY_FLAG 1u
#define GHOSTOS_RPC_KNOWN_FLAGS GHOSTOS_RPC_CAPABILITY_FLAG

typedef uint16_t ghostos_op;
enum {
    GHOSTOS_OP_YIELD = 1,
    GHOSTOS_OP_CLOCK_NOW = 2,
    GHOSTOS_OP_WAIT = 3,
    GHOSTOS_OP_WAKE = 4,
    GHOSTOS_OP_THREAD_SPAWN = 5,
    GHOSTOS_OP_THREAD_JOIN = 6,
    GHOSTOS_OP_THREAD_EXIT = 7,
    GHOSTOS_OP_MEMORY_MAP = 8,
    GHOSTOS_OP_MEMORY_UNMAP = 9,
    GHOSTOS_OP_IPC_MAP = 10,
    GHOSTOS_OP_IPC_NOTIFY = 11,
    GHOSTOS_OP_SYN_FS_OPEN = 12,
    GHOSTOS_OP_SYN_FS_CLOSE = 13,
    GHOSTOS_OP_SYN_FS_READ = 14,
    GHOSTOS_OP_SYN_FS_WRITE = 15,
    GHOSTOS_OP_SYN_FS_METADATA = 16,
    GHOSTOS_OP_SYN_FS_MKDIR = 17,
    GHOSTOS_OP_SYN_FS_RMDIR = 18,
    GHOSTOS_OP_SYN_FS_LINK = 19,
    GHOSTOS_OP_SYN_FS_LIST = 20,
    GHOSTOS_OP_SYN_FS_LINKS = 21,
    GHOSTOS_OP_SYN_FS_DELETE = 22,
    GHOSTOS_OP_RANDOM_GET = 23,
    GHOSTOS_OP_TERMINAL_READ = 24,
    GHOSTOS_OP_TERMINAL_WRITE = 25,
    GHOSTOS_OP_PROCESS_SPAWN = 26,
    GHOSTOS_OP_PROCESS_EXEC = 27,
    GHOSTOS_OP_PROCESS_WAIT = 28,
    GHOSTOS_OP_PROCESS_CANCEL = 29,
    GHOSTOS_OP_PROCESS_EXIT = 30,
    GHOSTOS_OP_PROCESS_STATUS = 31,
    GHOSTOS_OP_MEMORY_PROTECT = 32,
    GHOSTOS_OP_CAPABILITY_QUERY = 33,
    GHOSTOS_OP_PIPE_CREATE = 34,
    GHOSTOS_OP_PIPE_READ = 35,
    GHOSTOS_OP_PIPE_WRITE = 36,
    GHOSTOS_OP_PIPE_CLOSE = 37,
    GHOSTOS_OP_THREAD_TLS_GET = 38,
    GHOSTOS_OP_THREAD_TLS_SET = 39,
    GHOSTOS_OP_ARGUMENTS_READ = 40,
    GHOSTOS_OP_ENVIRONMENT_READ = 41,
    GHOSTOS_OP_SERVICE_READY = 42,
    GHOSTOS_OP_SERVICE_HEARTBEAT = 43,
    GHOSTOS_OP_SYSTEM_INFO = 44,
    GHOSTOS_OP_SHELL_POLL = 45,
    GHOSTOS_OP_REALTIME_NOW = 46,
    GHOSTOS_OP_SLEEP_UNTIL = 47,
    GHOSTOS_OP_SYN_FS_MAP = 48,
    GHOSTOS_OP_SYN_FS_UNMAP = 49,
    GHOSTOS_OP_LOGIN_COMPLETE = 50,
    GHOSTOS_OP_LOGIN_STATUS = 51,
    GHOSTOS_OP_LOGIN_START = 52,
    GHOSTOS_OP_LOGIN_CHALLENGE = 53,
    GHOSTOS_OP_LOGIN_TPM_CHALLENGE = 54,
    GHOSTOS_OP_LOGIN_TPM_COMPLETE = 55,
    GHOSTOS_OP_LOGIN_LOGOUT = 56,
    GHOSTOS_OP_LOGIN_WHOAMI = 57,
    GHOSTOS_OP_LOGIN_BOOTSTRAP_USERNAME = 58,
    GHOSTOS_OP_LOGIN_BOOTSTRAP_CREDENTIAL = 59,
    GHOSTOS_OP_LOGIN_BOOTSTRAP_CONFIRM = 60,
    GHOSTOS_OP_LOGIN_BOOTSTRAP_RECOVERY = 61,
    GHOSTOS_OP_LOGIN_REVOKE_IDENTITY = 62,
    GHOSTOS_OP_SHUTDOWN = 63,
    GHOSTOS_OP_WATCHDOG_DIAGNOSTICS = 64,
    GHOSTOS_OP_LOGIN_BRIDGE_READ = 65,
};

typedef uint8_t ghostos_rpc_method;
enum {
    GHOSTOS_RPC_METHOD_CLUSTER_STATE = 1,
    GHOSTOS_RPC_METHOD_SUBMIT_JOB = 2,
    GHOSTOS_RPC_METHOD_DELEGATE_CAPABILITY = 3,
    GHOSTOS_RPC_METHOD_TOPOLOGY_STATE = 4,
    GHOSTOS_RPC_METHOD_CLUSTER_SUMMARY = 5,
    GHOSTOS_RPC_METHOD_CLUSTER_MEMBERS = 6,
    GHOSTOS_RPC_METHOD_CLUSTER_INVITATIONS = 7,
    GHOSTOS_RPC_METHOD_CLUSTER_JOIN_PLAN = 8,
    GHOSTOS_RPC_METHOD_CLUSTER_LEAVE_PLAN = 9,
    GHOSTOS_RPC_METHOD_CLUSTER_HEALTH = 10,
    GHOSTOS_RPC_METHOD_CLUSTER_RESOURCES = 11,
    GHOSTOS_RPC_METHOD_CLUSTER_AUDIT = 12,
    GHOSTOS_RPC_METHOD_CLUSTER_CREATE = 13,
    GHOSTOS_RPC_METHOD_CLUSTER_JOIN = 14,
    GHOSTOS_RPC_METHOD_CLUSTER_LEAVE = 15,
    GHOSTOS_RPC_METHOD_CLUSTER_REMOVE = 16,
    GHOSTOS_RPC_METHOD_SUBSCRIBE = 17,
    GHOSTOS_RPC_METHOD_POLL = 18,
};

typedef uint16_t ghostos_rpc_status;
enum {
    GHOSTOS_RPC_STATUS_OK = 0,
    GHOSTOS_RPC_STATUS_INVALID_REQUEST = 1,
    GHOSTOS_RPC_STATUS_UNAUTHENTICATED = 2,
    GHOSTOS_RPC_STATUS_ACCESS_DENIED = 3,
    GHOSTOS_RPC_STATUS_NOT_FOUND = 4,
    GHOSTOS_RPC_STATUS_BUSY = 5,
    GHOSTOS_RPC_STATUS_CAPACITY = 6,
    GHOSTOS_RPC_STATUS_INTERNAL = 7,
    GHOSTOS_RPC_STATUS_PROTOCOL_MISMATCH = 8,
    GHOSTOS_RPC_STATUS_INVALID_FRAME = 9,
    GHOSTOS_RPC_STATUS_SCHEMA_MISMATCH = 10,
};

typedef uint64_t ghostos_capability;
typedef struct {
    uint32_t region;
    uint32_t offset;
    uint32_t length;
    bool writable;
} ghostos_shared_buffer;

typedef struct {
    uint16_t operation;
    uint16_t abi_version;
    uint16_t flags;
    uint16_t reserved;
    uint64_t capability;
    uint64_t arguments[6];
} ghostos_request;

typedef struct {
    uint32_t status;
    uint32_t flags;
    uint64_t values[4];
} ghostos_response;

_Static_assert(sizeof(ghostos_request) == 64, "request ABI size");
_Static_assert(offsetof(ghostos_request, capability) == 8, "request capability offset");
_Static_assert(offsetof(ghostos_request, arguments) == 16, "request arguments offset");
_Static_assert(sizeof(ghostos_response) == 40, "response ABI size");
_Static_assert(offsetof(ghostos_response, values) == 8, "response values offset");

/* Encode this structure explicitly; its in-memory layout is not the wire format. */
typedef struct {
    ghostos_rpc_method method;
    uint16_t flags;
    uint64_t request_id;
    uint32_t payload_bytes;
    ghostos_rpc_status status;
} ghostos_rpc_frame_header;

typedef enum {
    GHOSTOS_FRAME_OK,
    GHOSTOS_FRAME_BUFFER_TOO_SMALL,
    GHOSTOS_FRAME_INVALID_FLAGS,
    GHOSTOS_FRAME_INVALID_FRAME,
    GHOSTOS_FRAME_INVALID_LENGTH,
    GHOSTOS_FRAME_INVALID_MAGIC,
    GHOSTOS_FRAME_INVALID_STATUS,
    GHOSTOS_FRAME_SCHEMA_MISMATCH,
    GHOSTOS_FRAME_UNKNOWN_METHOD,
    GHOSTOS_FRAME_UNSUPPORTED_VERSION
} ghostos_frame_error;

extern const uint8_t ghostos_rpc_magic[4];
bool ghostos_operation_from_raw(uint16_t raw, ghostos_op *out);
bool ghostos_capability_from_raw(uint64_t raw, ghostos_capability *out);
ghostos_request ghostos_request_new(ghostos_op operation);
ghostos_request ghostos_request_with_capability(ghostos_request request, ghostos_capability capability);
ghostos_request ghostos_request_with_buffer(ghostos_request request, ghostos_shared_buffer buffer);
extern const ghostos_response ghostos_response_empty;
ghostos_frame_error ghostos_rpc_method_from_wire(uint8_t raw, ghostos_rpc_method *out);
ghostos_frame_error ghostos_rpc_status_from_wire(uint16_t raw, ghostos_rpc_status *out);
ghostos_status ghostos_rpc_public_status(ghostos_rpc_status status);
ghostos_frame_error ghostos_rpc_frame_encode(ghostos_rpc_frame_header header, uint8_t *output, size_t length);
ghostos_frame_error ghostos_rpc_frame_decode(const uint8_t *input, size_t length, ghostos_rpc_frame_header *out);
#endif
