#!/usr/bin/env python3
"""Check that the tracked review baseline matches the current repository shape."""

from __future__ import annotations

import argparse
import hashlib
import json
import pathlib
import re
import sys
import tomllib


ROOT = pathlib.Path(__file__).resolve().parent.parent
BASELINE_PATH = ROOT / "docs" / "review-baseline.toml"
CARGO_PATH = ROOT / "Cargo.toml"
IGNORED_DIRECTORIES = {".git", "build", "target"}
HEADING_PATTERN = re.compile(r"^#{1,6}[ \t]+.+$", re.MULTILINE)
CHECKBOX_PATTERN = re.compile(r"^- \[[ xX]\]", re.MULTILINE)


def json_value(value: object) -> str:
    return json.dumps(value, ensure_ascii=False)


def toml_array(values: list[object]) -> str:
    if not values:
        return "[]"
    return "[" + ", ".join(json_value(value) for value in values) + "]"


def roadmap_paths() -> list[str]:
    paths = []
    for path in ROOT.rglob("TODO*.md"):
        if any(part in IGNORED_DIRECTORIES for part in path.parts):
            continue
        paths.append(path.relative_to(ROOT).as_posix())
    return sorted(paths)


def workspace_snapshot() -> dict[str, object]:
    cargo = tomllib.loads(CARGO_PATH.read_text())
    workspace = cargo.get("workspace", {})
    members = list(workspace.get("members", []))
    manifests: list[dict[str, str]] = []

    for pattern in members:
        for match in sorted(ROOT.glob(pattern)):
            manifest = match if match.name == "Cargo.toml" else match / "Cargo.toml"
            if not manifest.is_file():
                continue
            package = tomllib.loads(manifest.read_text()).get("package", {})
            manifests.append(
                {
                    "path": manifest.relative_to(ROOT).as_posix(),
                    "package": str(package.get("name", "")),
                }
            )

    return {
        "resolver": str(workspace.get("resolver", "")),
        "members": members,
        "default_members": list(workspace.get("default-members", [])),
        "exclude": list(workspace.get("exclude", [])),
        "member_manifests": manifests,
    }


def roadmap_snapshot(path_string: str) -> dict[str, object]:
    path = ROOT / path_string
    text = path.read_text()
    headings = [line.strip() for line in HEADING_PATTERN.findall(text)]
    return {
        "path": path_string,
        "headings": headings,
        "checkbox_count": len(CHECKBOX_PATTERN.findall(text)),
    }


def digest(value: object) -> str:
    encoded = json.dumps(value, ensure_ascii=False, sort_keys=True).encode()
    return hashlib.sha256(encoded).hexdigest()


def current_snapshot() -> dict[str, object]:
    paths = roadmap_paths()
    workspace = workspace_snapshot()
    roadmaps = [roadmap_snapshot(path) for path in paths]
    return {
        "schema": 1,
        "workspace_manifest": "Cargo.toml",
        "roadmap_paths": paths,
        "workspace": {
            "digest": digest(workspace),
            "member_count": len(workspace["member_manifests"]),
        },
        "roadmap": [
            {
                "path": roadmap["path"],
                "heading_digest": digest(roadmap["headings"]),
                "heading_count": len(roadmap["headings"]),
                "checkbox_count": roadmap["checkbox_count"],
            }
            for roadmap in roadmaps
        ],
    }


def render(snapshot: dict[str, object]) -> str:
    workspace = snapshot["workspace"]
    lines = [
        "# Generated by scripts/validate-review-baseline.py --update.",
        "# Run the checker after changing workspace membership or roadmap structure.",
        f"schema = {snapshot['schema']}",
        f"workspace_manifest = {json_value(snapshot['workspace_manifest'])}",
        f"roadmap_paths = {toml_array(snapshot['roadmap_paths'])}",
        "",
        "[workspace]",
        f"digest = {json_value(workspace['digest'])}",
        f"member_count = {workspace['member_count']}",
    ]
    lines.append("")

    for roadmap in snapshot["roadmap"]:
        lines.extend(
            [
                "[[roadmap]]",
                f"path = {json_value(roadmap['path'])}",
                f"heading_digest = {json_value(roadmap['heading_digest'])}",
                f"heading_count = {roadmap['heading_count']}",
                f"checkbox_count = {roadmap['checkbox_count']}",
                "",
            ]
        )
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--check", action="store_true", help="fail when the baseline is stale")
    mode.add_argument("--update", action="store_true", help="write the current baseline")
    args = parser.parse_args()

    snapshot = current_snapshot()
    rendered = render(snapshot)

    if args.update:
        BASELINE_PATH.write_text(rendered)
        print(f"review baseline updated: {BASELINE_PATH.relative_to(ROOT)}")
        return 0

    if not BASELINE_PATH.is_file():
        print(f"review baseline missing: {BASELINE_PATH.relative_to(ROOT)}", file=sys.stderr)
        print("run python3 scripts/validate-review-baseline.py --update", file=sys.stderr)
        return 1

    try:
        recorded = tomllib.loads(BASELINE_PATH.read_text())
    except tomllib.TOMLDecodeError as exc:
        print(f"review baseline is invalid TOML: {exc}", file=sys.stderr)
        return 1

    if recorded != snapshot:
        print("review baseline is stale", file=sys.stderr)
        if recorded.get("workspace") != snapshot["workspace"]:
            print("workspace membership or package manifest shape changed", file=sys.stderr)
        if recorded.get("roadmap_paths") != snapshot["roadmap_paths"]:
            print("roadmap file set changed", file=sys.stderr)
        recorded_roadmaps = {
            entry.get("path"): entry for entry in recorded.get("roadmap", [])
        }
        for roadmap in snapshot["roadmap"]:
            if recorded_roadmaps.get(roadmap["path"]) != roadmap:
                print(f"roadmap structure changed: {roadmap['path']}", file=sys.stderr)
        print("run python3 scripts/validate-review-baseline.py --update", file=sys.stderr)
        return 1

    print(
        f"review baseline current: {len(snapshot['roadmap'])} roadmaps, "
        f"{snapshot['workspace']['member_count']} workspace members"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
