[package]
name = "ghostos-cookbook"
version = "0.1.0"
edition.workspace = true
publish = false

[dependencies]
ghostos-auth = { path = "../../crates/auth" }
ghostos-boot-protocol = { path = "../../crates/boot-protocol" }
ghostos-durability = { path = "../../crates/durability" }
ghostos-fabric = { path = "../../crates/fabric" }
ghostos-kernel = { path = "../../kernel" }
ghostos-netd = { path = "../../crates/netd" }
ghostos-rustd = { path = "../../crates/ghostos-rustd" }
ghostos-backup = { path = "../../crates/ghostos-backup" }
ghostos-ghostfs = { path = "../../crates/ghostfs" }
ghostos-system-model = { path = "../../crates/system-model" }
