[workspace]
resolver = "3"
members = [
    "crates/boot-protocol",
    "crates/host-filesystems",
    "crates/legacy-pc-drivers",
    "crates/platform-io",
    "crates/synfs",
    "crates/system-model",
    "kernel",
    "boot/uefi",
]
default-members = [
    "crates/boot-protocol",
    "crates/host-filesystems",
    "crates/legacy-pc-drivers",
    "crates/platform-io",
    "crates/synfs",
    "crates/system-model",
    "kernel",
]

[workspace.package]
edition = "2024"
license = "MIT OR Apache-2.0"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
lto = true
codegen-units = 1
