[package]
name = "ghostos-kernel"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[lib]
crate-type = ["rlib"]
path = "src/lib.rs"

[[bench]]
name = "lock_contention"
harness = false

[[bench]]
name = "hot_allocator"
harness = false

[[bench]]
name = "scalability"
harness = false

[[bin]]
name = "ghostos-kernel"
path = "src/main.rs"
test = false
bench = false

[dependencies]
ghostos-abi = { path = "../crates/abi" }
ghostos-app = { path = "../crates/app" }
ghostos-boot-protocol = { path = "../crates/boot-protocol" }
ghostos-fabric = { path = "../crates/fabric" }
ghostos-fsd = { path = "../crates/fsd" }
ghostos-legacy-pc-drivers = { path = "../crates/legacy-pc-drivers" }
ghostos-ipc = { path = "../crates/ipc" }
ghostos-init = { path = "../crates/init" }
ghostos-observability = { path = "../crates/observability" }
ghostos-numa = { path = "../crates/numa" }
ghostos-power = { path = "../crates/power" }
ghostos-shell = { path = "../crates/ghostos-shell" }
ghostos-status = { path = "../crates/status" }
ghostos-runtime = { path = "../crates/runtime" }
ghostos-ghostfs = { path = "../crates/ghostfs" }
ghostos-system-model = { path = "../crates/system-model" }

[dev-dependencies]
ghostos-test-support = { path = "../crates/test-support" }
