/* Generated by tools/generate_c_abi.py. Edit abi/ghostos-abi.toml. */
#include "ghostos/abi.h"

const uint8_t ghostos_rpc_magic[4] = {83, 89, 82, 80};
const ghostos_response ghostos_response_empty = {0};

bool ghostos_capability_from_raw(uint64_t raw, ghostos_capability *out) {
    if ((raw >> 32) == 0 || out == NULL) return false;
    *out = raw;
    return true;
}

ghostos_request ghostos_request_new(ghostos_op operation) {
    ghostos_request request = {0};
    request.operation = operation;
    request.abi_version = GHOSTOS_ABI_SCHEMA_VERSION;
    return request;
}
ghostos_request ghostos_request_with_capability(ghostos_request request, ghostos_capability capability) {
    request.capability = capability;
    return request;
}
ghostos_request ghostos_request_with_buffer(ghostos_request request, ghostos_shared_buffer buffer) {
    request.arguments[0] = buffer.region;
    request.arguments[1] = buffer.offset;
    request.arguments[2] = buffer.length;
    request.arguments[3] = buffer.writable;
    return request;
}

bool ghostos_operation_from_raw(uint16_t raw, ghostos_op *out) {
    if (out == NULL) return false;
    switch (raw) {
        case 1:
        case 2:
        case 3:
        case 4:
        case 5:
        case 6:
        case 7:
        case 8:
        case 9:
        case 10:
        case 11:
        case 12:
        case 13:
        case 14:
        case 15:
        case 16:
        case 17:
        case 18:
        case 19:
        case 20:
        case 21:
        case 22:
        case 23:
        case 24:
        case 25:
        case 26:
        case 27:
        case 28:
        case 29:
        case 30:
        case 31:
        case 32:
        case 33:
        case 34:
        case 35:
        case 36:
        case 37:
        case 38:
        case 39:
        case 40:
        case 41:
        case 42:
        case 43:
        case 44:
        case 45:
        case 46:
        case 47:
        case 48:
        case 49:
        case 50:
        case 51:
        case 52:
        case 53:
        case 54:
        case 55:
        case 56:
        case 57:
        case 58:
        case 59:
        case 60:
        case 61:
        case 62:
        case 63:
        case 64:
        case 65:
            *out = raw; return true;
        default: return false;
    }
}

ghostos_frame_error ghostos_rpc_method_from_wire(uint8_t raw, ghostos_rpc_method *out) {
    if (out == NULL) return GHOSTOS_FRAME_INVALID_FRAME;
    switch (raw) {
        case 1:
        case 2:
        case 3:
        case 4:
        case 5:
        case 6:
        case 7:
        case 8:
        case 9:
        case 10:
        case 11:
        case 12:
        case 13:
        case 14:
        case 15:
        case 16:
        case 17:
        case 18:
            *out = raw; return GHOSTOS_FRAME_OK;
        default: return GHOSTOS_FRAME_UNKNOWN_METHOD;
    }
}

ghostos_frame_error ghostos_rpc_status_from_wire(uint16_t raw, ghostos_rpc_status *out) {
    if (out == NULL) return GHOSTOS_FRAME_INVALID_FRAME;
    switch (raw) {
        case 0:
        case 1:
        case 2:
        case 3:
        case 4:
        case 5:
        case 6:
        case 7:
        case 8:
        case 9:
        case 10:
            *out = raw; return GHOSTOS_FRAME_OK;
        default: return GHOSTOS_FRAME_INVALID_STATUS;
    }
}

ghostos_status ghostos_rpc_public_status(ghostos_rpc_status status) {
    switch (status) {
        case GHOSTOS_RPC_STATUS_OK: return GHOSTOS_STATUS_NORMAL;
        case GHOSTOS_RPC_STATUS_INVALID_REQUEST: return GHOSTOS_STATUS_INVALID_ARGUMENT;
        case GHOSTOS_RPC_STATUS_UNAUTHENTICATED: return GHOSTOS_STATUS_ACCESS_DENIED;
        case GHOSTOS_RPC_STATUS_ACCESS_DENIED: return GHOSTOS_STATUS_ACCESS_DENIED;
        case GHOSTOS_RPC_STATUS_NOT_FOUND: return GHOSTOS_STATUS_NOT_FOUND;
        case GHOSTOS_RPC_STATUS_BUSY: return GHOSTOS_STATUS_BUSY;
        case GHOSTOS_RPC_STATUS_CAPACITY: return GHOSTOS_STATUS_NO_SPACE;
        case GHOSTOS_RPC_STATUS_INTERNAL: return GHOSTOS_STATUS_INTERNAL;
        case GHOSTOS_RPC_STATUS_PROTOCOL_MISMATCH: return GHOSTOS_STATUS_PROTOCOL_MISMATCH;
        case GHOSTOS_RPC_STATUS_INVALID_FRAME: return GHOSTOS_STATUS_INVALID_ARGUMENT;
        case GHOSTOS_RPC_STATUS_SCHEMA_MISMATCH: return GHOSTOS_STATUS_PROTOCOL_MISMATCH;
        default: return GHOSTOS_STATUS_INVALID_ARGUMENT;
    }
}

static void write_be(uint8_t *out, uint64_t value, size_t bytes) {
    for (size_t i = 0; i < bytes; ++i) out[bytes - i - 1] = (uint8_t)(value >> (i * 8));
}
static uint64_t read_be(const uint8_t *input, size_t bytes) {
    uint64_t value = 0;
    for (size_t i = 0; i < bytes; ++i) value = (value << 8) | input[i];
    return value;
}

ghostos_frame_error ghostos_rpc_frame_encode(ghostos_rpc_frame_header header, uint8_t *output, size_t length) {
    if (output == NULL || length < GHOSTOS_RPC_FRAME_HEADER_BYTES ||
        (header.flags & ~GHOSTOS_RPC_KNOWN_FLAGS) != 0 ||
        header.payload_bytes > GHOSTOS_RPC_MAX_FRAME_BYTES - GHOSTOS_RPC_FRAME_HEADER_BYTES)
        return GHOSTOS_FRAME_INVALID_LENGTH;
    ghostos_rpc_method method;
    ghostos_rpc_status status;
    ghostos_frame_error error = ghostos_rpc_method_from_wire(header.method, &method);
    if (error != GHOSTOS_FRAME_OK) return error;
    error = ghostos_rpc_status_from_wire(header.status, &status);
    if (error != GHOSTOS_FRAME_OK) return error;
    for (size_t i = 0; i < GHOSTOS_RPC_FRAME_HEADER_BYTES; ++i) output[i] = 0;
    for (size_t i = 0; i < 4; ++i) output[i] = ghostos_rpc_magic[i];
    output[4] = GHOSTOS_RPC_PROTOCOL_VERSION;
    output[5] = header.method;
    write_be(output + 6, header.flags, 2);
    write_be(output + 8, header.request_id, 8);
    write_be(output + 16, header.payload_bytes, 4);
    write_be(output + 20, header.status, 2);
    return GHOSTOS_FRAME_OK;
}

ghostos_frame_error ghostos_rpc_frame_decode(const uint8_t *input, size_t length, ghostos_rpc_frame_header *out) {
    if (input == NULL || length < GHOSTOS_RPC_FRAME_HEADER_BYTES) return GHOSTOS_FRAME_BUFFER_TOO_SMALL;
    for (size_t i = 0; i < 4; ++i)
        if (input[i] != ghostos_rpc_magic[i]) return GHOSTOS_FRAME_INVALID_MAGIC;
    if (input[4] != GHOSTOS_RPC_PROTOCOL_VERSION) return GHOSTOS_FRAME_UNSUPPORTED_VERSION;
    ghostos_rpc_frame_header header = {0};
    header.flags = (uint16_t)read_be(input + 6, 2);
    header.payload_bytes = (uint32_t)read_be(input + 16, 4);
    if ((header.flags & ~GHOSTOS_RPC_KNOWN_FLAGS) != 0) return GHOSTOS_FRAME_INVALID_FLAGS;
    if (header.payload_bytes > GHOSTOS_RPC_MAX_FRAME_BYTES - GHOSTOS_RPC_FRAME_HEADER_BYTES ||
        length < GHOSTOS_RPC_FRAME_HEADER_BYTES + (size_t)header.payload_bytes)
        return GHOSTOS_FRAME_INVALID_LENGTH;
    ghostos_frame_error error = ghostos_rpc_method_from_wire(input[5], &header.method);
    if (error != GHOSTOS_FRAME_OK) return error;
    header.request_id = read_be(input + 8, 8);
    error = ghostos_rpc_status_from_wire((uint16_t)read_be(input + 20, 2), &header.status);
    if (error != GHOSTOS_FRAME_OK) return error;
    if (out == NULL) return GHOSTOS_FRAME_INVALID_FRAME;
    *out = header;
    return GHOSTOS_FRAME_OK;
}
