#include "ghostos/address_space.h"

static bool add(uint64_t a, uint64_t b, uint64_t *out) { if (UINT64_MAX - a < b) return false; *out = a + b; return true; }
static bool same_map(ghostos_mapping a, ghostos_mapping b) { return a.base == b.base && a.size == b.size; }
static bool region_end(const ghostos_as_region *r, uint64_t *end) { return add(r->base, r->size, end); }
static bool contains(uint64_t base, uint64_t size, uint64_t at, uint64_t length) { uint64_t end, requested; return add(base, size, &end) && add(at, length, &requested) && at >= base && requested <= end; }
static bool overlaps(uint64_t a, uint64_t an, uint64_t b, uint64_t bn) { uint64_t ae, be; return !add(a, an, &ae) || !add(b, bn, &be) || (a < be && b < ae); }
static size_t free_slots(const ghostos_address_space *s) { size_t n=0; for(size_t i=0;i<GHOSTOS_MAX_ADDRESS_SPACE_REGIONS;i++) if(!s->regions[i].used)n++; return n; }
static bool any_overlap(const ghostos_address_space *s,uint64_t b,uint64_t n) { for(size_t i=0;i<GHOSTOS_MAX_ADDRESS_SPACE_REGIONS;i++) if(s->regions[i].used&&overlaps(s->regions[i].base,s->regions[i].size,b,n))return true; return false; }
static ghostos_as_error insert(ghostos_address_space *s, ghostos_as_region r) { for(size_t i=0;i<GHOSTOS_MAX_ADDRESS_SPACE_REGIONS;i++) if(!s->regions[i].used){r.used=true;s->regions[i]=r;return GHOSTOS_AS_OK;} return GHOSTOS_AS_CAPACITY; }
static bool owns(const ghostos_address_space *s,ghostos_mapping m,uint64_t b,uint64_t n) { for(size_t i=0;i<GHOSTOS_MAX_ADDRESS_SPACE_REGIONS;i++){const ghostos_as_region*r=&s->regions[i];if(r->used&&same_map(r->owner,m)&&contains(r->base,r->size,b,n))return true;}return false; }
static bool mapped_contains(const ghostos_address_space *s,uint64_t b,uint64_t n) { for(size_t i=0;i<GHOSTOS_MAX_ADDRESS_SPACE_REGIONS;i++){const ghostos_as_region*r=&s->regions[i];if(r->used&&r->has_permissions&&contains(r->base,r->size,b,n))return true;}return false; }
static bool violates_wx(const ghostos_address_space*s,uint64_t b,uint64_t n,uint8_t p,int ignored){for(size_t i=0;i<GHOSTOS_MAX_ADDRESS_SPACE_REGIONS;i++){const ghostos_as_region*r=&s->regions[i];if((int)i==ignored||!r->used||!r->has_permissions||!overlaps(r->base,r->size,b,n))continue;if(((p&GHOSTOS_PERM_WRITE)&&(r->permissions&GHOSTOS_PERM_EXECUTE))||((p&GHOSTOS_PERM_EXECUTE)&&(r->permissions&GHOSTOS_PERM_WRITE)))return true;}return false;}
bool ghostos_as_is_user_range(uint64_t a,uint64_t n){uint64_t e;return a>=GHOSTOS_USER_SPACE_START&&add(a,n,&e)&&e<=GHOSTOS_USER_SPACE_END;}
bool ghostos_as_is_kernel_range(uint64_t a,uint64_t n){uint64_t e;return a>=GHOSTOS_KERNEL_SPACE_START&&add(a,n,&e)&&e<=GHOSTOS_KERNEL_SPACE_END;}
bool ghostos_as_page_table_root(uint64_t f,ghostos_page_table_root*out){if(!out||!f||f%GHOSTOS_PAGE_SIZE)return false;out->frame=f;return true;}
void ghostos_as_init(ghostos_address_space*s,uint32_t id,ghostos_page_table_root root,uint64_t seed){s->id=id;s->root=root;s->aslr_state=seed;for(size_t i=0;i<GHOSTOS_MAX_ADDRESS_SPACE_REGIONS;i++)s->regions[i].used=false;}
bool ghostos_as_can_access(const ghostos_address_space*s,uint64_t a,uint64_t n,ghostos_memory_access access){if(!ghostos_as_is_user_range(a,n))return false;uint8_t bit=access==GHOSTOS_ACCESS_READ?GHOSTOS_PERM_READ:access==GHOSTOS_ACCESS_WRITE?GHOSTOS_PERM_WRITE:GHOSTOS_PERM_EXECUTE;for(size_t i=0;i<GHOSTOS_MAX_ADDRESS_SPACE_REGIONS;i++){const ghostos_as_region*r=&s->regions[i];if(r->used&&r->has_permissions&&contains(r->base,r->size,a,n)&&(r->permissions&bit))return true;}return false;}
static bool align_up(uint64_t v,uint64_t a,uint64_t*out){uint64_t x;if(!add(v,a-1,&x))return false;*out=x&~(a-1);return true;}
ghostos_as_error ghostos_as_reserve(ghostos_address_space*s,ghostos_mapping_request q,ghostos_mapping*out){if(!q.size||q.alignment<GHOSTOS_PAGE_SIZE||(q.alignment&(q.alignment-1)))return GHOSTOS_AS_INVALID_REQUEST;uint64_t base;if(q.fixed){if(!q.has_preferred_base||q.preferred_base%q.alignment)return GHOSTOS_AS_INVALID_REQUEST;base=q.preferred_base;}else{base=q.has_preferred_base?q.preferred_base:GHOSTOS_USER_SPACE_START;if(s->aslr_state&&!q.has_preferred_base){s->aslr_state^=s->aslr_state<<13;s->aslr_state^=s->aslr_state>>7;s->aslr_state^=s->aslr_state<<17;uint64_t avail=GHOSTOS_USER_SPACE_END-GHOSTOS_USER_SPACE_START;if(q.size<avail){uint64_t slots=(avail-q.size)/q.alignment;base=GHOSTOS_USER_SPACE_START+(s->aslr_state%(slots?slots:1))*q.alignment;}}if(base<GHOSTOS_USER_SPACE_START)base=GHOSTOS_USER_SPACE_START;bool found=false;for(size_t i=0;i<GHOSTOS_MAX_ADDRESS_SPACE_REGIONS;i++){if(!align_up(base,q.alignment,&base))return GHOSTOS_AS_MAPPING_OVERFLOW;if(ghostos_as_is_user_range(base,q.size)&&!any_overlap(s,base,q.size)){found=true;break;}uint64_t end;if(!add(base,q.size,&end))return GHOSTOS_AS_MAPPING_OVERFLOW;uint64_t next=end;bool hit=false;for(size_t j=0;j<GHOSTOS_MAX_ADDRESS_SPACE_REGIONS;j++){const ghostos_as_region*r=&s->regions[j];if(r->used&&overlaps(r->base,r->size,base,q.size)){uint64_t re;if(region_end(r,&re)&&(!hit||re>next)){next=re;hit=true;}}}if(!hit)return GHOSTOS_AS_MAPPING_OVERFLOW;base=next;}if(!found)return GHOSTOS_AS_CAPACITY;}if(!ghostos_as_is_user_range(base,q.size)||any_overlap(s,base,q.size))return q.fixed?GHOSTOS_AS_MAPPING_CONFLICT:GHOSTOS_AS_MAPPING_OVERFLOW;ghostos_mapping m={base,q.size};ghostos_as_error e=ghostos_as_claim(s,m);if(e==GHOSTOS_AS_OK&&out)*out=m;return e;}
ghostos_as_error ghostos_as_claim(ghostos_address_space*s,ghostos_mapping m){if(!m.size||!ghostos_as_is_user_range(m.base,m.size)||any_overlap(s,m.base,m.size))return GHOSTOS_AS_MAPPING_CONFLICT;ghostos_as_region r={0};r.owner=m;r.base=m.base;r.size=m.size;return insert(s,r);}
ghostos_as_error ghostos_as_map_backing(ghostos_address_space*s,uint64_t auth,ghostos_physical_range b,bool w,ghostos_mapping*out){uint64_t end;if(!b.length||b.start%GHOSTOS_PAGE_SIZE||b.length%GHOSTOS_PAGE_SIZE||!add(b.start,b.length,&end))return GHOSTOS_AS_INVALID_MAPPING;ghostos_mapping m;ghostos_mapping_request q={b.length,GHOSTOS_PAGE_SIZE,0,false,false};ghostos_as_error e=ghostos_as_reserve(s,q,&m);if(e)return e;for(size_t i=0;i<GHOSTOS_MAX_ADDRESS_SPACE_REGIONS;i++){ghostos_as_region*r=&s->regions[i];if(r->used&&same_map(r->owner,m)&&!r->has_permissions){r->has_permissions=true;r->permissions=GHOSTOS_PERM_READ|(w?GHOSTOS_PERM_WRITE:0);r->has_backing=true;r->backing=b;r->authority=auth;if(out)*out=m;return GHOSTOS_AS_OK;}}ghostos_as_release(s,m);return GHOSTOS_AS_INVALID_MAPPING;}
ghostos_as_error ghostos_as_record_stack(ghostos_address_space*s,ghostos_mapping m,uint64_t b,uint64_t n,uint8_t guards){uint64_t gs=(uint64_t)guards*GHOSTOS_PAGE_SIZE,gb;if(b%GHOSTOS_PAGE_SIZE||!n||n%GHOSTOS_PAGE_SIZE||!ghostos_as_is_user_range(b,n)||b<gs)return GHOSTOS_AS_INVALID_MAPPING;gb=b-gs;if(gs&&!ghostos_as_is_user_range(gb,gs))return GHOSTOS_AS_INVALID_MAPPING;if(any_overlap(s,b,n)||(gs&&any_overlap(s,gb,gs)))return GHOSTOS_AS_MAPPING_CONFLICT;if(free_slots(s)<(size_t)(1+(gs!=0)))return GHOSTOS_AS_CAPACITY;if(gs){ghostos_as_region g={0};g.owner=m;g.base=gb;g.size=gs;g.guard=true;ghostos_as_error e=insert(s,g);if(e)return e;}ghostos_as_region r={0};r.owner=m;r.base=b;r.size=n;r.has_permissions=true;r.permissions=GHOSTOS_PERM_READ|GHOSTOS_PERM_WRITE;r.stack=true;return insert(s,r);}
ghostos_stack_error ghostos_as_stack_growth_page(const ghostos_address_space*s,uint64_t a,uint64_t*out){uint64_t page=a&~(GHOSTOS_PAGE_SIZE-1);size_t gi=GHOSTOS_MAX_ADDRESS_SPACE_REGIONS,si=gi;uint64_t ge=0;for(size_t i=0;i<GHOSTOS_MAX_ADDRESS_SPACE_REGIONS;i++){const ghostos_as_region*g=&s->regions[i];if(g->used&&g->guard&&contains(g->base,g->size,page,GHOSTOS_PAGE_SIZE)){if(!region_end(g,&ge)||page!=ge-GHOSTOS_PAGE_SIZE)return GHOSTOS_STACK_NOT_GUARD;gi=i;for(size_t j=0;j<GHOSTOS_MAX_ADDRESS_SPACE_REGIONS;j++){const ghostos_as_region*r=&s->regions[j];if(r->used&&r->stack&&same_map(r->owner,g->owner)&&r->base==ge){si=j;break;}}break;}}if(gi==GHOSTOS_MAX_ADDRESS_SPACE_REGIONS||si==GHOSTOS_MAX_ADDRESS_SPACE_REGIONS)return GHOSTOS_STACK_NOT_GUARD;const ghostos_as_region*st=&s->regions[si];if(st->base<GHOSTOS_PAGE_SIZE)return GHOSTOS_STACK_OVERFLOW;uint64_t nb=st->base-GHOSTOS_PAGE_SIZE;if(!ghostos_as_is_user_range(nb,GHOSTOS_PAGE_SIZE))return GHOSTOS_STACK_OVERFLOW;for(size_t i=0;i<GHOSTOS_MAX_ADDRESS_SPACE_REGIONS;i++)if(i!=gi&&i!=si&&s->regions[i].used&&overlaps(s->regions[i].base,s->regions[i].size,nb,GHOSTOS_PAGE_SIZE))return GHOSTOS_STACK_COLLISION;if(out)*out=nb;return GHOSTOS_STACK_OK;}
ghostos_stack_error ghostos_as_grow_stack(ghostos_address_space*s,uint64_t a,ghostos_stack_growth*out){uint64_t page;ghostos_stack_error e=ghostos_as_stack_growth_page(s,a,&page);if(e)return e;for(size_t i=0;i<GHOSTOS_MAX_ADDRESS_SPACE_REGIONS;i++){ghostos_as_region*g=&s->regions[i];uint64_t end;if(!g->used||!g->guard||!region_end(g,&end)||end-GHOSTOS_PAGE_SIZE!=page)continue;for(size_t j=0;j<GHOSTOS_MAX_ADDRESS_SPACE_REGIONS;j++){ghostos_as_region*st=&s->regions[j];if(st->used&&st->stack&&same_map(st->owner,g->owner)&&st->base==end){if(g->base<GHOSTOS_PAGE_SIZE||st->size>UINT64_MAX-GHOSTOS_PAGE_SIZE)return GHOSTOS_STACK_OVERFLOW;g->base-=GHOSTOS_PAGE_SIZE;st->base=page;st->size+=GHOSTOS_PAGE_SIZE;if(out){out->page=page;out->new_stack_base=page;out->new_guard_base=g->base;out->has_new_guard_base=true;}return GHOSTOS_STACK_OK;}}}return GHOSTOS_STACK_NOT_GUARD;}
ghostos_as_error ghostos_as_clone_cow(ghostos_address_space*p,uint32_t id,ghostos_page_table_root root,ghostos_address_space*c){if(!id||id==p->id)return GHOSTOS_AS_INVALID_REQUEST;for(size_t i=0;i<GHOSTOS_MAX_ADDRESS_SPACE_REGIONS;i++){ghostos_as_region*r=&p->regions[i];if(r->used&&r->has_permissions&&r->has_backing&&(r->permissions&GHOSTOS_PERM_WRITE)){r->permissions&=(uint8_t)~GHOSTOS_PERM_WRITE;r->copy_on_write=true;}}*c=*p;c->id=id;c->root=root;return GHOSTOS_AS_OK;}
ghostos_as_error ghostos_as_cow_mapping(const ghostos_address_space*s,uint64_t a,uint64_t*page,uint64_t*frame){uint64_t p=a&~(GHOSTOS_PAGE_SIZE-1);for(size_t i=0;i<GHOSTOS_MAX_ADDRESS_SPACE_REGIONS;i++){const ghostos_as_region*r=&s->regions[i];if(r->used&&r->copy_on_write&&r->has_backing&&contains(r->base,r->size,p,GHOSTOS_PAGE_SIZE)){uint64_t off=p-r->base,f;if(!add(r->backing.start,off,&f))return GHOSTOS_AS_INVALID_MAPPING;if(page)*page=p;if(frame)*frame=f;return GHOSTOS_AS_OK;}}return GHOSTOS_AS_NOT_COPY_ON_WRITE;}
ghostos_as_error ghostos_as_can_replace_cow_page(const ghostos_address_space*s,uint64_t a){uint64_t p=a&~(GHOSTOS_PAGE_SIZE-1);for(size_t i=0;i<GHOSTOS_MAX_ADDRESS_SPACE_REGIONS;i++){const ghostos_as_region*r=&s->regions[i];uint64_t end,right;if(r->used&&r->copy_on_write&&r->has_backing&&contains(r->base,r->size,p,GHOSTOS_PAGE_SIZE)){if(!region_end(r,&end)||!add(p,GHOSTOS_PAGE_SIZE,&right))return GHOSTOS_AS_MAPPING_OVERFLOW;size_t extra=(p!=r->base)+(end>right);return free_slots(s)>=extra?GHOSTOS_AS_OK:GHOSTOS_AS_CAPACITY;}}return GHOSTOS_AS_NOT_COPY_ON_WRITE;}
ghostos_as_error ghostos_as_replace_cow_page(ghostos_address_space*s,uint64_t a,uint64_t nf,ghostos_physical_range*out){if(nf%GHOSTOS_PAGE_SIZE)return GHOSTOS_AS_INVALID_MAPPING;uint64_t p=a&~(GHOSTOS_PAGE_SIZE-1);size_t ix=GHOSTOS_MAX_ADDRESS_SPACE_REGIONS;for(size_t i=0;i<GHOSTOS_MAX_ADDRESS_SPACE_REGIONS;i++)if(s->regions[i].used&&s->regions[i].copy_on_write&&s->regions[i].has_backing&&contains(s->regions[i].base,s->regions[i].size,p,GHOSTOS_PAGE_SIZE)){ix=i;break;}if(ix==GHOSTOS_MAX_ADDRESS_SPACE_REGIONS)return GHOSTOS_AS_NOT_COPY_ON_WRITE;ghostos_as_region o=s->regions[ix];uint64_t end,right,off=p-o.base;if(!region_end(&o,&end)||!add(p,GHOSTOS_PAGE_SIZE,&right))return GHOSTOS_AS_MAPPING_OVERFLOW;size_t extra=(p!=o.base)+(end>right);if(free_slots(s)<extra)return GHOSTOS_AS_CAPACITY;uint64_t old;if(!add(o.backing.start,off,&old))return GHOSTOS_AS_INVALID_MAPPING;ghostos_as_region priv=o;priv.base=p;priv.size=GHOSTOS_PAGE_SIZE;priv.permissions|=GHOSTOS_PERM_WRITE;priv.backing.start=nf;priv.backing.length=GHOSTOS_PAGE_SIZE;priv.copy_on_write=false;ghostos_as_region left=o,right_r=o;bool has_left=p!=o.base,has_right=end>right;if(has_left){left.size=p-o.base;left.backing.length=left.size;}if(has_right){right_r.base=right;right_r.size=end-right;right_r.backing.start=o.backing.start+off+GHOSTOS_PAGE_SIZE;right_r.backing.length=right_r.size;}s->regions[ix]=has_left?left:priv;if(has_left){ghostos_as_error e=insert(s,priv);if(e)return e;}if(has_right){ghostos_as_error e=insert(s,right_r);if(e)return e;}if(out){out->start=old;out->length=GHOSTOS_PAGE_SIZE;}return GHOSTOS_AS_OK;}
ghostos_as_error ghostos_as_unmap_backing(ghostos_address_space*s,uint64_t auth,uint64_t a,uint64_t n,ghostos_physical_range*out){if(a%GHOSTOS_PAGE_SIZE||!n||n%GHOSTOS_PAGE_SIZE)return GHOSTOS_AS_INVALID_MAPPING;for(size_t i=0;i<GHOSTOS_MAX_ADDRESS_SPACE_REGIONS;i++){ghostos_as_region*r=&s->regions[i];if(r->used&&r->base==a&&r->size==n&&r->authority==auth&&r->has_backing){if(out)*out=r->backing;r->used=false;return GHOSTOS_AS_OK;}}return GHOSTOS_AS_NOT_FOUND;}
ghostos_as_error ghostos_as_map_segment(ghostos_address_space*s,ghostos_mapping m,ghostos_runtime_segment x,size_t source){if(!x.memory_size||x.file_size>x.memory_size||x.file_size!=(uint64_t)source||((x.permissions&GHOSTOS_PERM_WRITE)&&(x.permissions&GHOSTOS_PERM_EXECUTE))||violates_wx(s,x.address,x.memory_size,x.permissions,-1)||!owns(s,m,x.address,x.memory_size))return GHOSTOS_AS_INVALID_MAPPING;ghostos_as_region r={0};r.owner=m;r.base=x.address;r.size=x.memory_size;r.has_permissions=true;r.permissions=x.permissions;return insert(s,r);}
ghostos_as_error ghostos_as_zero_fill(const ghostos_address_space*s,ghostos_mapping m,uint64_t a,uint64_t n){return n&&owns(s,m,a,n)?GHOSTOS_AS_OK:GHOSTOS_AS_INVALID_MAPPING;}
ghostos_as_error ghostos_as_relocate(const ghostos_address_space*s,ghostos_mapping m,uint64_t a){return owns(s,m,a,sizeof(uint64_t))?GHOSTOS_AS_OK:GHOSTOS_AS_INVALID_MAPPING;}
ghostos_as_error ghostos_as_protect(ghostos_address_space*s,ghostos_mapping m,uint64_t a,uint64_t n,uint8_t p){int found=-1;for(size_t i=0;i<GHOSTOS_MAX_ADDRESS_SPACE_REGIONS;i++){ghostos_as_region*r=&s->regions[i];if(r->used&&same_map(r->owner,m)&&r->base==a&&r->size==n&&r->has_permissions){found=(int)i;break;}}if(!n||((p&GHOSTOS_PERM_WRITE)&&(p&GHOSTOS_PERM_EXECUTE))||violates_wx(s,a,n,p,found)||!owns(s,m,a,n))return GHOSTOS_AS_INVALID_MAPPING;if(found>=0){s->regions[found].permissions=p;return GHOSTOS_AS_OK;}ghostos_as_region r={0};r.owner=m;r.base=a;r.size=n;r.has_permissions=true;r.permissions=p;return insert(s,r);}
ghostos_as_error ghostos_as_record_region(ghostos_address_space*s,ghostos_mapping m,uint64_t b,uint64_t n,uint8_t p){if(!n||((p&GHOSTOS_PERM_WRITE)&&(p&GHOSTOS_PERM_EXECUTE))||violates_wx(s,b,n,p,-1)||!ghostos_as_is_user_range(b,n))return GHOSTOS_AS_INVALID_MAPPING;ghostos_as_region r={0};r.owner=m;r.base=b;r.size=n;r.has_permissions=true;r.permissions=p;return insert(s,r);}
ghostos_as_error ghostos_as_install_context(const ghostos_address_space*s,ghostos_process_context c){uint64_t stack=c.stack_pointer?c.stack_pointer-1:0;if(!ghostos_as_can_access(s,c.entry,1,GHOSTOS_ACCESS_EXECUTE)||!ghostos_as_can_access(s,stack,1,GHOSTOS_ACCESS_WRITE)||ghostos_as_can_access(s,stack,1,GHOSTOS_ACCESS_EXECUTE)||!mapped_contains(s,c.heap_base,c.heap_size)||(c.has_tls_pointer&&!mapped_contains(s,c.tls_pointer,1)))return GHOSTOS_AS_INVALID_CONTEXT;return GHOSTOS_AS_OK;}
void ghostos_as_release(ghostos_address_space*s,ghostos_mapping m){for(size_t i=0;i<GHOSTOS_MAX_ADDRESS_SPACE_REGIONS;i++)if(s->regions[i].used&&same_map(s->regions[i].owner,m))s->regions[i].used=false;}
void ghostos_as_table_init(ghostos_address_space_table*t){for(size_t i=0;i<GHOSTOS_MAX_ADDRESS_SPACES;i++)t->slots[i].used=false;}
ghostos_as_error ghostos_as_table_create(ghostos_address_space_table*t,uint32_t id,ghostos_page_table_root root,uint64_t seed){if(!id)return GHOSTOS_AS_INVALID_REQUEST;size_t free_i=GHOSTOS_MAX_ADDRESS_SPACES;for(size_t i=0;i<GHOSTOS_MAX_ADDRESS_SPACES;i++){if(t->slots[i].used&&(t->slots[i].space.id==id||t->slots[i].space.root.frame==root.frame))return GHOSTOS_AS_MAPPING_CONFLICT;if(!t->slots[i].used&&free_i==GHOSTOS_MAX_ADDRESS_SPACES)free_i=i;}if(free_i==GHOSTOS_MAX_ADDRESS_SPACES)return GHOSTOS_AS_CAPACITY;ghostos_as_init(&t->slots[free_i].space,id,root,seed);t->slots[free_i].used=true;return GHOSTOS_AS_OK;}
ghostos_address_space *ghostos_as_table_get(ghostos_address_space_table*t,uint32_t id){for(size_t i=0;i<GHOSTOS_MAX_ADDRESS_SPACES;i++)if(t->slots[i].used&&t->slots[i].space.id==id)return &t->slots[i].space;return NULL;}
const ghostos_address_space *ghostos_as_table_get_const(const ghostos_address_space_table*t,uint32_t id){for(size_t i=0;i<GHOSTOS_MAX_ADDRESS_SPACES;i++)if(t->slots[i].used&&t->slots[i].space.id==id)return &t->slots[i].space;return NULL;}
static bool shared_backing(const ghostos_address_space*a,const ghostos_address_space*b){for(size_t i=0;i<GHOSTOS_MAX_ADDRESS_SPACE_REGIONS;i++){const ghostos_as_region*x=&a->regions[i];if(!x->used||!x->has_backing)continue;for(size_t j=0;j<GHOSTOS_MAX_ADDRESS_SPACE_REGIONS;j++){const ghostos_as_region*y=&b->regions[j];if(y->used&&y->has_backing&&overlaps(x->backing.start,x->backing.length,y->backing.start,y->backing.length))return true;}}return false;}
ghostos_isolation_error ghostos_as_table_check_isolation(const ghostos_address_space_table*t,uint32_t a,uint32_t b){if(a==b)return GHOSTOS_ISOLATION_SAME_SPACE;const ghostos_address_space*x=ghostos_as_table_get_const(t,a),*y=ghostos_as_table_get_const(t,b);if(!x||!y)return GHOSTOS_ISOLATION_NOT_FOUND;if(x->root.frame==y->root.frame)return GHOSTOS_ISOLATION_SHARED_TABLE;if(shared_backing(x,y))return GHOSTOS_ISOLATION_SHARED_BACKING;return GHOSTOS_ISOLATION_OK;}
ghostos_as_error ghostos_as_table_destroy(ghostos_address_space_table*t,uint32_t id){for(size_t i=0;i<GHOSTOS_MAX_ADDRESS_SPACES;i++)if(t->slots[i].used&&t->slots[i].space.id==id){t->slots[i].used=false;return GHOSTOS_AS_OK;}return GHOSTOS_AS_NOT_FOUND;}
