#include "ghostos/capability.h"

#define NO_SLOT UINT32_MAX
#define MICROS_PER_SECOND UINT64_C(1000000)

static uint64_t sat_add(uint64_t a,uint64_t b){return UINT64_MAX-a<b?UINT64_MAX:a+b;}
static uint64_t sat_mul(uint64_t a,uint64_t b){return a&&b>UINT64_MAX/a?UINT64_MAX:a*b;}
static uint64_t sat_sub(uint64_t a,uint64_t b){return a<b?0:a-b;}
static uint64_t cap_handle(uint32_t slot,uint32_t generation){return ((uint64_t)generation<<32)|slot;}
static uint32_t handle_slot(uint64_t handle){return (uint32_t)handle;}
static uint32_t handle_generation(uint64_t handle){return (uint32_t)(handle>>32);}
static bool rights_contains(uint16_t rights,uint16_t needed){return (rights&needed)==needed;}

bool ghostos_capability_handle_from_raw(uint64_t raw,ghostos_capability_handle*out){if(!handle_generation(raw))return false;if(out)*out=raw;return true;}
bool ghostos_capability_rights_valid(uint16_t rights){return (rights&~GHOSTOS_RIGHT_ALL)==0;}
bool ghostos_capability_range_new(uint64_t start,uint64_t length,ghostos_capability_range*out){if(!length||UINT64_MAX-start<length)return false;if(out)*out=(ghostos_capability_range){start,length};return true;}
bool ghostos_capability_range_contains(ghostos_capability_range a,ghostos_capability_range b){return b.start>=a.start&&sat_add(b.start,b.length)<=sat_add(a.start,a.length);}
bool ghostos_capability_range_overlaps(ghostos_capability_range a,ghostos_capability_range b){return a.start<sat_add(b.start,b.length)&&b.start<sat_add(a.start,a.length);}
ghostos_capability_object ghostos_capability_object_make(ghostos_capability_object_kind kind,uint8_t scope,uint32_t value32,uint64_t value0,uint64_t value1){return (ghostos_capability_object){kind,scope,value32,value0,value1};}
bool ghostos_capability_object_equal(ghostos_capability_object a,ghostos_capability_object b){return a.kind==b.kind&&a.scope==b.scope&&a.value32==b.value32&&a.value0==b.value0&&a.value1==b.value1;}

ghostos_quota_policy ghostos_quota_policy_default(void){return (ghostos_quota_policy){{1024,4096},{128,128},{UINT64_C(268435456),UINT64_C(536870912)},UINT64_C(1073741824)};}
bool ghostos_quota_policy_valid(ghostos_quota_policy p){return p.ipc.capacity&&p.ipc.refill_per_second&&p.page_fault.capacity&&p.page_fault.refill_per_second&&p.memory.capacity&&p.memory.refill_per_second&&p.max_memory_bytes;}

static void quota_init(ghostos_capability_quota*q,ghostos_quota_policy p){q->policy=p;for(size_t i=0;i<3;i++){atomic_flag_clear(&q->locks[i]);q->buckets[i]=(ghostos_quota_bucket_state){i==0?p.ipc.capacity:i==1?p.page_fault.capacity:p.memory.capacity,0,0};}atomic_init(&q->clock,0);atomic_init(&q->memory_in_use,0);}
static void quota_configure(ghostos_capability_quota*q,ghostos_quota_policy p){q->policy=p;for(size_t i=0;i<3;i++)q->buckets[i]=(ghostos_quota_bucket_state){i==0?p.ipc.capacity:i==1?p.page_fault.capacity:p.memory.capacity,0,0};atomic_store_explicit(&q->memory_in_use,0,memory_order_relaxed);}
static void quota_lock(ghostos_capability_quota*q,size_t i){while(atomic_flag_test_and_set_explicit(&q->locks[i],memory_order_acquire))atomic_signal_fence(memory_order_seq_cst);}
static void quota_unlock(ghostos_capability_quota*q,size_t i){atomic_flag_clear_explicit(&q->locks[i],memory_order_release);}
static ghostos_quota_bucket_config bucket_config(ghostos_quota_policy p,size_t r){return r==0?p.ipc:r==1?p.page_fault:p.memory;}
static void update_clock(ghostos_capability_quota*q,uint64_t now){uint64_t old=atomic_load_explicit(&q->clock,memory_order_relaxed);while(old<now&&!atomic_compare_exchange_weak_explicit(&q->clock,&old,now,memory_order_relaxed,memory_order_relaxed)){} }
static ghostos_quota_result quota_consume(ghostos_capability_quota*q,size_t r,uint64_t now,uint64_t amount){if(amount==0)return (ghostos_quota_result){0,GHOSTOS_CAP_QUOTA_ALLOWED};update_clock(q,now);quota_lock(q,r);ghostos_quota_bucket_config c=bucket_config(q->policy,r);ghostos_quota_bucket_state*s=&q->buckets[r];ghostos_quota_result result={0,GHOSTOS_CAP_QUOTA_ALLOWED};uint64_t in_use=atomic_load_explicit(&q->memory_in_use,memory_order_relaxed);if(r==2&&(amount>q->policy.max_memory_bytes||in_use>q->policy.max_memory_bytes-amount)){result.decision=GHOSTOS_CAP_QUOTA_REJECTED;}else if(amount>c.capacity){result.decision=GHOSTOS_CAP_QUOTA_REJECTED;}else{
        if(now<s->last_refill_us){s->last_refill_us=now;s->remainder=0;}else{uint64_t elapsed=now-s->last_refill_us;uint64_t produced=sat_add(sat_mul(elapsed,c.refill_per_second),s->remainder);uint64_t added=produced/MICROS_PER_SECOND;s->remainder=produced%MICROS_PER_SECOND;s->tokens=sat_add(s->tokens,added);if(s->tokens>c.capacity)s->tokens=c.capacity;s->last_refill_us=now;}
        if(s->tokens>=amount){s->tokens-=amount;if(r==2)atomic_store_explicit(&q->memory_in_use,sat_add(in_use,amount),memory_order_relaxed);}else{uint64_t missing=amount-s->tokens;uint64_t numerator=sat_mul(missing,MICROS_PER_SECOND);uint64_t rounded=sat_add(numerator,c.refill_per_second-1);uint64_t delay=rounded/c.refill_per_second;if(!delay)delay=1;result.decision=GHOSTOS_CAP_QUOTA_THROTTLED;result.retry_after_us=delay;}}
    quota_unlock(q,r);return result;}
static void quota_refund(ghostos_capability_quota*q,size_t r,uint64_t amount){if(!amount)return;quota_lock(q,r);ghostos_quota_bucket_config c=bucket_config(q->policy,r);ghostos_quota_bucket_state*s=&q->buckets[r];s->tokens=sat_add(s->tokens,amount);if(s->tokens>c.capacity)s->tokens=c.capacity;if(r==2)atomic_store_explicit(&q->memory_in_use,sat_sub(atomic_load_explicit(&q->memory_in_use,memory_order_relaxed),amount),memory_order_relaxed);quota_unlock(q,r);}
static void quota_release_memory(ghostos_capability_quota*q,uint64_t amount){if(!amount)return;quota_lock(q,2);atomic_store_explicit(&q->memory_in_use,sat_sub(atomic_load_explicit(&q->memory_in_use,memory_order_relaxed),amount),memory_order_relaxed);quota_unlock(q,2);}

void ghostos_capability_space_init(ghostos_capability_space*s,size_t capacity,ghostos_capability_event_hook events,void*ctx){if(capacity>GHOSTOS_MAX_CAPABILITIES)capacity=GHOSTOS_MAX_CAPABILITIES;s->capacity=capacity;s->event_hook=events;s->event_context=ctx;ghostos_quota_policy p=ghostos_quota_policy_default();for(size_t i=0;i<GHOSTOS_MAX_CAPABILITIES;i++){s->entries[i]=(ghostos_capability_descriptor){0,false,{0},NO_SLOT,NO_SLOT,NO_SLOT};quota_init(&s->quotas[i],p);}}
size_t ghostos_capability_capacity(const ghostos_capability_space*s){return s->capacity;}
static void event(ghostos_capability_space*s,uint8_t level,uint16_t op,uint64_t handle,uint32_t owner,uint64_t value,ghostos_status status,bool trace){if(s->event_hook)s->event_hook(s->event_context,level,op,handle,owner,value,status,trace);}
static ghostos_capability_error valid_slot(const ghostos_capability_space*s,uint64_t h,uint32_t*out){uint32_t slot=handle_slot(h);if(!handle_generation(h)||slot>=s->capacity)return GHOSTOS_CAP_INVALID_HANDLE;const ghostos_capability_descriptor*e=&s->entries[slot];if(!e->occupied||e->generation!=handle_generation(h))return GHOSTOS_CAP_INVALID_HANDLE;if(out)*out=slot;return GHOSTOS_CAP_OK;}
static ghostos_capability_error authorize_handle(const ghostos_capability_space*s,uint32_t caller,uint64_t h,uint16_t required,ghostos_capability_info*out){uint32_t slot;ghostos_capability_error e=valid_slot(s,h,&slot);if(e){event((ghostos_capability_space*)s,1,3,h,caller,0,GHOSTOS_STATUS_INVALID_ARGUMENT,false);return e;}ghostos_capability_info i=s->entries[slot].info;if(i.owner!=caller||!rights_contains(i.rights,required)){event((ghostos_capability_space*)s,1,3,h,caller,0,GHOSTOS_STATUS_ACCESS_DENIED,false);return GHOSTOS_CAP_ACCESS_DENIED;}event((ghostos_capability_space*)s,0,3,h,caller,0,GHOSTOS_STATUS_NORMAL,false);event((ghostos_capability_space*)s,0,3,h,caller,0,GHOSTOS_STATUS_NORMAL,true);if(out)*out=i;return GHOSTOS_CAP_OK;}
static bool is_descendant(const ghostos_capability_space*s,uint32_t slot,uint64_t ancestor){bool has=s->entries[slot].info.has_parent;uint64_t parent=s->entries[slot].info.parent;for(size_t i=0;has&&i<s->capacity;i++){if(parent==ancestor)return true;uint32_t p;if(valid_slot(s,parent,&p))return false;has=s->entries[p].info.has_parent;parent=s->entries[p].info.parent;}return false;}
static ghostos_capability_error insert_cap(ghostos_capability_space*s,uint32_t owner,ghostos_capability_object obj,uint16_t rights,bool has_parent,uint64_t parent,bool has_backing,ghostos_capability_range backing,uint64_t*out){if(!rights)return GHOSTOS_CAP_EMPTY_RIGHTS;if(!ghostos_capability_rights_valid(rights))return GHOSTOS_CAP_RIGHTS_ESCALATION;size_t slot=s->capacity;for(size_t i=0;i<s->capacity;i++)if(!s->entries[i].occupied){slot=i;break;}if(slot==s->capacity)return GHOSTOS_CAP_FULL;uint32_t parent_slot=NO_SLOT;if(has_parent){ghostos_capability_error e=valid_slot(s,parent,&parent_slot);if(e)return e;}uint32_t generation=s->entries[slot].generation+1;if(!generation)generation=1;uint32_t sibling=parent_slot==NO_SLOT?NO_SLOT:s->entries[parent_slot].first_child;ghostos_quota_policy policy=parent_slot==NO_SLOT?ghostos_quota_policy_default():s->quotas[parent_slot].policy;s->entries[slot]=(ghostos_capability_descriptor){generation,true,{owner,obj,rights,has_parent,parent,has_backing,backing},parent_slot,NO_SLOT,sibling};quota_configure(&s->quotas[slot],policy);if(parent_slot!=NO_SLOT)s->entries[parent_slot].first_child=(uint32_t)slot;uint64_t handle=cap_handle((uint32_t)slot,generation);event(s,0,1,handle,owner,rights,GHOSTOS_STATUS_NORMAL,false);event(s,0,1,handle,owner,1,GHOSTOS_STATUS_NORMAL,true);if(out)*out=handle;return GHOSTOS_CAP_OK;}

ghostos_capability_error ghostos_capability_mint_root(ghostos_capability_space*s,uint32_t owner,ghostos_capability_object obj,uint16_t rights,uint64_t*out){return insert_cap(s,owner,obj,rights,false,0,false,(ghostos_capability_range){0,0},out);}
ghostos_capability_error ghostos_capability_mint_untyped(ghostos_capability_space*s,uint32_t owner,ghostos_capability_range r,uint16_t rights,uint64_t*out){return insert_cap(s,owner,ghostos_capability_object_make(GHOSTOS_OBJECT_UNTYPED,0,0,r.start,r.length),rights,false,0,true,r,out);}
ghostos_capability_error ghostos_capability_mint_mmio(ghostos_capability_space*s,uint32_t owner,ghostos_capability_range r,uint16_t rights,uint64_t*out){return insert_cap(s,owner,ghostos_capability_object_make(GHOSTOS_OBJECT_MMIO,0,0,r.start,r.length),rights,false,0,true,r,out);}
ghostos_capability_error ghostos_capability_retype_memory(ghostos_capability_space*s,uint32_t caller,uint64_t source,uint32_t owner,uint32_t region,ghostos_capability_range memory,uint16_t rights,uint64_t*out){ghostos_capability_info info;ghostos_capability_error e=authorize_handle(s,caller,source,GHOSTOS_RIGHT_CREATE,&info);if(e)return e;if(info.object.kind!=GHOSTOS_OBJECT_UNTYPED)return GHOSTOS_CAP_ACCESS_DENIED;ghostos_capability_range untyped={info.object.value0,info.object.value1};if(!rights)return GHOSTOS_CAP_EMPTY_RIGHTS;if(!rights_contains(info.rights,rights))return GHOSTOS_CAP_RIGHTS_ESCALATION;if(!ghostos_capability_range_contains(untyped,memory))return GHOSTOS_CAP_ACCESS_DENIED;uint32_t source_slot;if(valid_slot(s,source,&source_slot))return GHOSTOS_CAP_INVALID_HANDLE;for(size_t i=0;i<s->capacity;i++){ghostos_capability_descriptor*d=&s->entries[i];if(i!=source_slot&&d->occupied&&is_descendant(s,(uint32_t)i,source)&&d->info.has_backing&&ghostos_capability_range_overlaps(d->info.backing,memory))return GHOSTOS_CAP_ACCESS_DENIED;}return insert_cap(s,owner,ghostos_capability_object_make(GHOSTOS_OBJECT_MEMORY_REGION,0,region,0,0),rights,true,source,true,memory,out);}
ghostos_capability_error ghostos_capability_delegate(ghostos_capability_space*s,uint32_t caller,uint64_t source,uint32_t owner,uint16_t rights,uint64_t*out){ghostos_capability_info info;ghostos_capability_error e=authorize_handle(s,caller,source,GHOSTOS_RIGHT_DELEGATE,&info);if(e)return e;if(!rights)return GHOSTOS_CAP_EMPTY_RIGHTS;if(!rights_contains(info.rights,rights))return GHOSTOS_CAP_RIGHTS_ESCALATION;return insert_cap(s,owner,info.object,rights,true,source,info.has_backing,info.backing,out);}
ghostos_capability_error ghostos_capability_drop_rights(ghostos_capability_space*s,uint32_t caller,uint64_t h,uint16_t rights,uint16_t*out){uint32_t slot;ghostos_capability_error e=valid_slot(s,h,&slot);if(e)return e;ghostos_capability_info*i=&s->entries[slot].info;if(i->owner!=caller)return GHOSTOS_CAP_ACCESS_DENIED;uint16_t r=i->rights&(uint16_t)~rights;if(!r)return GHOSTOS_CAP_EMPTY_RIGHTS;i->rights=r;event(s,0,4,h,caller,r,GHOSTOS_STATUS_NORMAL,false);if(out)*out=r;return GHOSTOS_CAP_OK;}
ghostos_capability_error ghostos_capability_authorize(const ghostos_capability_space*s,uint32_t caller,uint64_t h,ghostos_capability_object obj,uint16_t required){ghostos_capability_info info;ghostos_capability_error e=authorize_handle(s,caller,h,required,&info);return e?e:ghostos_capability_object_equal(info.object,obj)?GHOSTOS_CAP_OK:GHOSTOS_CAP_ACCESS_DENIED;}
ghostos_capability_error ghostos_capability_authorize_mapping(const ghostos_capability_space*s,uint32_t caller,uint64_t h,uint32_t region,bool writable,bool executable){uint16_t r=GHOSTOS_RIGHT_MAP|GHOSTOS_RIGHT_READ;if(writable)r|=GHOSTOS_RIGHT_WRITE;if(executable)r|=GHOSTOS_RIGHT_EXECUTE;return ghostos_capability_authorize(s,caller,h,ghostos_capability_object_make(GHOSTOS_OBJECT_MEMORY_REGION,0,region,0,0),r);}
ghostos_capability_error ghostos_capability_inspect(const ghostos_capability_space*s,uint32_t caller,uint64_t h,ghostos_capability_info*out){return authorize_handle(s,caller,h,0,out);}

ghostos_capability_error ghostos_capability_configure_quota(ghostos_capability_space*s,uint32_t caller,uint64_t h,ghostos_quota_policy p){uint32_t slot;ghostos_capability_error e=valid_slot(s,h,&slot);if(e)return e;ghostos_capability_info i=s->entries[slot].info;if(i.owner!=caller||!rights_contains(i.rights,GHOSTOS_RIGHT_CONTROL))return GHOSTOS_CAP_ACCESS_DENIED;if(!ghostos_quota_policy_valid(p))return GHOSTOS_CAP_INVALID_QUOTA;quota_configure(&s->quotas[slot],p);return GHOSTOS_CAP_OK;}
ghostos_capability_error ghostos_capability_quota_policy(const ghostos_capability_space*s,uint32_t caller,uint64_t h,ghostos_quota_policy*out){uint32_t slot;ghostos_capability_error e=valid_slot(s,h,&slot);if(e)return e;if(s->entries[slot].info.owner!=caller)return GHOSTOS_CAP_ACCESS_DENIED;if(out)*out=s->quotas[slot].policy;return GHOSTOS_CAP_OK;}
ghostos_capability_error ghostos_capability_quota_usage(const ghostos_capability_space*s,uint32_t caller,uint64_t h,ghostos_quota_usage*out){uint32_t slot;ghostos_capability_error e=valid_slot(s,h,&slot);if(e)return e;if(s->entries[slot].info.owner!=caller)return GHOSTOS_CAP_ACCESS_DENIED;if(out)*out=(ghostos_quota_usage){atomic_load_explicit(&s->quotas[slot].memory_in_use,memory_order_relaxed),s->quotas[slot].policy.max_memory_bytes};return GHOSTOS_CAP_OK;}
static size_t quota_chain(const ghostos_capability_space*s,uint32_t slot,uint32_t chain[GHOSTOS_MAX_CAPABILITIES]){size_t n=0;uint32_t current=slot;while(n<s->capacity){chain[n++]=current;uint32_t p=s->entries[current].parent_slot;if(p==NO_SLOT)break;current=p;}return n;}
ghostos_capability_error ghostos_capability_consume_quota(ghostos_capability_space*s,uint32_t caller,uint64_t h,ghostos_capability_quota_resource r,uint64_t now,uint64_t amount,ghostos_quota_result*out){uint32_t slot;ghostos_capability_error e=valid_slot(s,h,&slot);if(e)return e;if(s->entries[slot].info.owner!=caller)return GHOSTOS_CAP_ACCESS_DENIED;if((unsigned)r>2)return GHOSTOS_CAP_INVALID_QUOTA;uint32_t chain[GHOSTOS_MAX_CAPABILITIES];size_t n=quota_chain(s,slot,chain),charged=0;ghostos_quota_result result={0,GHOSTOS_CAP_QUOTA_ALLOWED};for(;charged<n;charged++){result=quota_consume(&s->quotas[chain[charged]],r,now,amount);if(result.decision!=GHOSTOS_CAP_QUOTA_ALLOWED)break;}if(result.decision!=GHOSTOS_CAP_QUOTA_ALLOWED){for(size_t i=0;i<charged;i++)quota_refund(&s->quotas[chain[i]],r,amount);}if(out)*out=result;return GHOSTOS_CAP_OK;}
ghostos_capability_error ghostos_capability_refund_quota(ghostos_capability_space*s,uint32_t caller,uint64_t h,ghostos_capability_quota_resource r,uint64_t amount){uint32_t slot;ghostos_capability_error e=valid_slot(s,h,&slot);if(e)return e;if(s->entries[slot].info.owner!=caller)return GHOSTOS_CAP_ACCESS_DENIED;if((unsigned)r>2)return GHOSTOS_CAP_INVALID_QUOTA;uint32_t chain[GHOSTOS_MAX_CAPABILITIES];size_t n=quota_chain(s,slot,chain);for(size_t i=0;i<n;i++)quota_refund(&s->quotas[chain[i]],r,amount);return GHOSTOS_CAP_OK;}
ghostos_capability_error ghostos_capability_release_memory(ghostos_capability_space*s,uint32_t caller,uint64_t h,uint64_t amount){uint32_t slot;ghostos_capability_error e=valid_slot(s,h,&slot);if(e)return e;if(s->entries[slot].info.owner!=caller)return GHOSTOS_CAP_ACCESS_DENIED;uint32_t chain[GHOSTOS_MAX_CAPABILITIES];size_t n=quota_chain(s,slot,chain);for(size_t i=0;i<n;i++)quota_release_memory(&s->quotas[chain[i]],amount);return GHOSTOS_CAP_OK;}

static bool handle_for_slot(const ghostos_capability_space*s,uint32_t slot,uint64_t*out){if(slot==NO_SLOT||slot>=s->capacity||!s->entries[slot].occupied)return false;if(out)*out=cap_handle(slot,s->entries[slot].generation);return true;}
ghostos_capability_error ghostos_capability_get_links(const ghostos_capability_space*s,uint32_t caller,uint64_t h,ghostos_capability_links*out){ghostos_capability_error e=authorize_handle(s,caller,h,0,0);if(e)return e;uint32_t slot;if(valid_slot(s,h,&slot))return GHOSTOS_CAP_INVALID_HANDLE;ghostos_capability_descriptor d=s->entries[slot];ghostos_capability_links l={0};l.has_parent=d.info.has_parent;l.parent=d.info.parent;l.has_first_child=handle_for_slot(s,d.first_child,&l.first_child);l.has_next_sibling=handle_for_slot(s,d.next_sibling,&l.next_sibling);if(out)*out=l;return GHOSTOS_CAP_OK;}

static void vacate(ghostos_capability_space*s,uint32_t slot){uint32_t parent=s->entries[slot].parent_slot,sibling=s->entries[slot].next_sibling;if(parent<s->capacity){uint32_t child=s->entries[parent].first_child;if(child==slot)s->entries[parent].first_child=sibling;else for(size_t i=0;i<s->capacity&&child!=NO_SLOT;i++){uint32_t next=s->entries[child].next_sibling;if(next==slot){s->entries[child].next_sibling=sibling;break;}child=next;}}s->entries[slot].occupied=false;quota_configure(&s->quotas[slot],ghostos_quota_policy_default());s->entries[slot].parent_slot=NO_SLOT;s->entries[slot].first_child=NO_SLOT;s->entries[slot].next_sibling=NO_SLOT;}
static size_t revoke_descendants(ghostos_capability_space*s,uint64_t authority,ghostos_capability_revoke_hook hook,void*ctx){bool revoke[GHOSTOS_MAX_CAPABILITIES]={0};for(size_t i=0;i<s->capacity;i++)revoke[i]=s->entries[i].occupied&&is_descendant(s,(uint32_t)i,authority);size_t n=0;for(size_t i=0;i<s->capacity;i++)if(revoke[i]){if(hook)hook(ctx,s->entries[i].info);vacate(s,(uint32_t)i);n++;}return n;}
static ghostos_capability_error revoke_authorized(ghostos_capability_space*s,uint32_t caller,uint64_t h,ghostos_capability_revoke_hook hook,void*ctx,size_t*out){ghostos_capability_error e=authorize_handle(s,caller,h,GHOSTOS_RIGHT_REVOKE,0);if(e)return e;size_t n=revoke_descendants(s,h,hook,ctx);event(s,0,2,h,caller,n,GHOSTOS_STATUS_NORMAL,false);event(s,0,2,h,caller,2,GHOSTOS_STATUS_NORMAL,true);if(out)*out=n;return GHOSTOS_CAP_OK;}
ghostos_capability_error ghostos_capability_revoke(ghostos_capability_space*s,uint32_t caller,uint64_t h,size_t*out){return revoke_authorized(s,caller,h,0,0,out);}
ghostos_capability_error ghostos_capability_revoke_with_hook(ghostos_capability_space*s,uint32_t caller,uint64_t h,ghostos_capability_revoke_hook hook,void*ctx,size_t*out){return revoke_authorized(s,caller,h,hook,ctx,out);}
ghostos_capability_error ghostos_capability_revoke_remote_memory(ghostos_capability_space*s,uint32_t caller,uint64_t h,uint64_t resource,size_t*out){ghostos_capability_error e=ghostos_capability_authorize(s,caller,h,ghostos_capability_object_make(GHOSTOS_OBJECT_DISTRIBUTED_RESOURCE,0,0,resource,0),GHOSTOS_RIGHT_REVOKE);if(e)return e;size_t n=revoke_descendants(s,h,0,0);event(s,0,2,h,caller,n,GHOSTOS_STATUS_NORMAL,false);event(s,0,2,h,caller,2,GHOSTOS_STATUS_NORMAL,true);if(out)*out=n;return GHOSTOS_CAP_OK;}
ghostos_capability_error ghostos_capability_delete(ghostos_capability_space*s,uint32_t caller,uint64_t h,size_t*out){ghostos_capability_error e=authorize_handle(s,caller,h,0,0);if(e)return e;size_t n=revoke_descendants(s,h,0,0);uint32_t slot;if(valid_slot(s,h,&slot))return GHOSTOS_CAP_INVALID_HANDLE;vacate(s,slot);event(s,0,2,h,caller,n+1,GHOSTOS_STATUS_NORMAL,false);event(s,0,2,h,caller,2,GHOSTOS_STATUS_NORMAL,true);if(out)*out=n+1;return GHOSTOS_CAP_OK;}
size_t ghostos_capability_used(const ghostos_capability_space*s){size_t n=0;for(size_t i=0;i<s->capacity;i++)n+=s->entries[i].occupied;return n;}
size_t ghostos_capability_entries(const ghostos_capability_space*s,ghostos_capability_entry_callback cb,void*ctx){size_t n=0;for(size_t i=0;i<s->capacity;i++)if(s->entries[i].occupied){n++;if(cb&&!cb(ctx,cap_handle((uint32_t)i,s->entries[i].generation),s->entries[i].info))break;}return n;}
bool ghostos_capability_check_invariants(const ghostos_capability_space*s){for(size_t slot=0;slot<s->capacity;slot++){const ghostos_capability_descriptor*e=&s->entries[slot];if(!e->occupied)continue;if(!e->generation||!e->info.rights||!ghostos_capability_rights_valid(e->info.rights))return false;if(!e->info.has_parent){if(e->parent_slot!=NO_SLOT)return false;}else{uint32_t p;if(valid_slot(s,e->info.parent,&p)||e->parent_slot!=p||!rights_contains(s->entries[p].info.rights,e->info.rights))return false;if(e->info.has_backing&&(!s->entries[p].info.has_backing||!ghostos_capability_range_contains(s->entries[p].info.backing,e->info.backing)))return false;}if(e->first_child!=NO_SLOT&&(e->first_child>=s->capacity||!s->entries[e->first_child].occupied||s->entries[e->first_child].parent_slot!=slot))return false;}
    for(size_t slot=0;slot<s->capacity;slot++){const ghostos_capability_descriptor*e=&s->entries[slot];if(!e->occupied||!e->info.has_parent)continue;uint32_t child=s->entries[e->parent_slot].first_child;bool found=false;for(size_t i=0;i<s->capacity&&child!=NO_SLOT;i++){if(child==slot){found=true;break;}if(child>=s->capacity||!s->entries[child].occupied||s->entries[child].parent_slot!=e->parent_slot)return false;child=s->entries[child].next_sibling;}if(!found)return false;}return true;}
