// DO NOT EDIT. Generated by tools/generate_abi.py from abi/synos-abi.toml.

pub const ABI_SCHEMA_VERSION: u16 = 1;
pub const ABI_REVISION: u16 = 5;
pub const RPC_PROTOCOL_VERSION: u8 = 1;
pub const RPC_MAGIC: [u8; 4] = [83, 89, 82, 80];
pub const RPC_FRAME_HEADER_BYTES: usize = 24;
pub const RPC_MAX_FRAME_BYTES: usize = 4096;
pub const RPC_CAPABILITY_FLAG: u16 = 1;
pub const RPC_KNOWN_FLAGS: u16 = RPC_CAPABILITY_FLAG;

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
#[repr(u16)]
pub enum Operation {
    Yield = 1,
    ClockNow = 2,
    Wait = 3,
    Wake = 4,
    ThreadSpawn = 5,
    ThreadJoin = 6,
    ThreadExit = 7,
    MemoryMap = 8,
    MemoryUnmap = 9,
    IpcMap = 10,
    IpcNotify = 11,
    SynFsOpen = 12,
    SynFsClose = 13,
    SynFsRead = 14,
    SynFsWrite = 15,
    SynFsMetadata = 16,
    SynFsMkdir = 17,
    SynFsRmdir = 18,
    SynFsLink = 19,
    SynFsList = 20,
    SynFsLinks = 21,
    SynFsDelete = 22,
    RandomGet = 23,
    TerminalRead = 24,
    TerminalWrite = 25,
    ProcessSpawn = 26,
    ProcessExec = 27,
    ProcessWait = 28,
    ProcessCancel = 29,
    ProcessExit = 30,
    ProcessStatus = 31,
    MemoryProtect = 32,
    CapabilityQuery = 33,
    PipeCreate = 34,
    PipeRead = 35,
    PipeWrite = 36,
    PipeClose = 37,
    ThreadTlsGet = 38,
    ThreadTlsSet = 39,
    ArgumentsRead = 40,
    EnvironmentRead = 41,
    ServiceReady = 42,
    ServiceHeartbeat = 43,
    SystemInfo = 44,
    ShellPoll = 45,
    RealtimeNow = 46,
    SleepUntil = 47,
    SynFsMap = 48,
    SynFsUnmap = 49,
    LoginComplete = 50,
}

impl Operation {
    pub const fn from_raw(raw: u16) -> Option<Self> {
        match raw {
            1 => Some(Self::Yield),
            2 => Some(Self::ClockNow),
            3 => Some(Self::Wait),
            4 => Some(Self::Wake),
            5 => Some(Self::ThreadSpawn),
            6 => Some(Self::ThreadJoin),
            7 => Some(Self::ThreadExit),
            8 => Some(Self::MemoryMap),
            9 => Some(Self::MemoryUnmap),
            10 => Some(Self::IpcMap),
            11 => Some(Self::IpcNotify),
            12 => Some(Self::SynFsOpen),
            13 => Some(Self::SynFsClose),
            14 => Some(Self::SynFsRead),
            15 => Some(Self::SynFsWrite),
            16 => Some(Self::SynFsMetadata),
            17 => Some(Self::SynFsMkdir),
            18 => Some(Self::SynFsRmdir),
            19 => Some(Self::SynFsLink),
            20 => Some(Self::SynFsList),
            21 => Some(Self::SynFsLinks),
            22 => Some(Self::SynFsDelete),
            23 => Some(Self::RandomGet),
            24 => Some(Self::TerminalRead),
            25 => Some(Self::TerminalWrite),
            26 => Some(Self::ProcessSpawn),
            27 => Some(Self::ProcessExec),
            28 => Some(Self::ProcessWait),
            29 => Some(Self::ProcessCancel),
            30 => Some(Self::ProcessExit),
            31 => Some(Self::ProcessStatus),
            32 => Some(Self::MemoryProtect),
            33 => Some(Self::CapabilityQuery),
            34 => Some(Self::PipeCreate),
            35 => Some(Self::PipeRead),
            36 => Some(Self::PipeWrite),
            37 => Some(Self::PipeClose),
            38 => Some(Self::ThreadTlsGet),
            39 => Some(Self::ThreadTlsSet),
            40 => Some(Self::ArgumentsRead),
            41 => Some(Self::EnvironmentRead),
            42 => Some(Self::ServiceReady),
            43 => Some(Self::ServiceHeartbeat),
            44 => Some(Self::SystemInfo),
            45 => Some(Self::ShellPoll),
            46 => Some(Self::RealtimeNow),
            47 => Some(Self::SleepUntil),
            48 => Some(Self::SynFsMap),
            49 => Some(Self::SynFsUnmap),
            50 => Some(Self::LoginComplete),
            _ => None,
        }
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
#[repr(transparent)]
pub struct Capability(u64);

impl Capability {
    pub const fn from_raw(raw: u64) -> Option<Self> {
        if raw >> 32 == 0 { None } else { Some(Self(raw)) }
    }

    pub const fn raw(self) -> u64 { self.0 }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
#[repr(C)]
pub struct Request {
    pub operation: u16,
    pub abi_version: u16,
    pub flags: u16,
    pub reserved: u16,
    pub capability: u64,
    pub arguments: [u64; 6],
}

impl Request {
    pub const fn new(operation: Operation) -> Self {
        Self {
            operation: operation as u16,
            abi_version: ABI_SCHEMA_VERSION,
            flags: 0,
            reserved: 0,
            capability: 0,
            arguments: [0; 6],
        }
    }

    pub const fn with_capability(mut self, capability: Capability) -> Self {
        self.capability = capability.raw();
        self
    }

    pub const fn with_buffer(mut self, buffer: synos_ipc::SharedBuffer) -> Self {
        self.arguments[0] = buffer.region.raw() as u64;
        self.arguments[1] = buffer.offset as u64;
        self.arguments[2] = buffer.length as u64;
        self.arguments[3] = buffer.writable as u64;
        self
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
#[repr(C)]
pub struct Response {
    pub status: u32,
    pub flags: u32,
    pub values: [u64; 4],
}

impl Response {
    pub const EMPTY: Self = Self { status: 0, flags: 0, values: [0; 4] };
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
#[repr(u8)]
pub enum RpcMethod {
    ClusterState = 1,
    SubmitJob = 2,
    DelegateCapability = 3,
    TopologyState = 4,
    ClusterSummary = 5,
    ClusterMembers = 6,
    ClusterInvitations = 7,
    ClusterJoinPlan = 8,
    ClusterLeavePlan = 9,
    ClusterHealth = 10,
    ClusterResources = 11,
    ClusterAudit = 12,
    ClusterCreate = 13,
    ClusterJoin = 14,
    ClusterLeave = 15,
    ClusterRemove = 16,
    Subscribe = 17,
    Poll = 18,
}

impl RpcMethod {
    pub const fn from_wire(raw: u8) -> Result<Self, FrameError> {
        match raw {
            1 => Ok(Self::ClusterState),
            2 => Ok(Self::SubmitJob),
            3 => Ok(Self::DelegateCapability),
            4 => Ok(Self::TopologyState),
            5 => Ok(Self::ClusterSummary),
            6 => Ok(Self::ClusterMembers),
            7 => Ok(Self::ClusterInvitations),
            8 => Ok(Self::ClusterJoinPlan),
            9 => Ok(Self::ClusterLeavePlan),
            10 => Ok(Self::ClusterHealth),
            11 => Ok(Self::ClusterResources),
            12 => Ok(Self::ClusterAudit),
            13 => Ok(Self::ClusterCreate),
            14 => Ok(Self::ClusterJoin),
            15 => Ok(Self::ClusterLeave),
            16 => Ok(Self::ClusterRemove),
            17 => Ok(Self::Subscribe),
            18 => Ok(Self::Poll),
            _ => Err(FrameError::UnknownMethod),
        }
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
#[repr(u16)]
pub enum RpcStatus {
    Ok = 0,
    InvalidRequest = 1,
    Unauthenticated = 2,
    AccessDenied = 3,
    NotFound = 4,
    Busy = 5,
    Capacity = 6,
    Internal = 7,
    ProtocolMismatch = 8,
    InvalidFrame = 9,
    SchemaMismatch = 10,
}

impl RpcStatus {
    pub const fn from_wire(raw: u16) -> Result<Self, FrameError> {
        match raw {
            0 => Ok(Self::Ok),
            1 => Ok(Self::InvalidRequest),
            2 => Ok(Self::Unauthenticated),
            3 => Ok(Self::AccessDenied),
            4 => Ok(Self::NotFound),
            5 => Ok(Self::Busy),
            6 => Ok(Self::Capacity),
            7 => Ok(Self::Internal),
            8 => Ok(Self::ProtocolMismatch),
            9 => Ok(Self::InvalidFrame),
            10 => Ok(Self::SchemaMismatch),
            _ => Err(FrameError::InvalidStatus),
        }
    }

    pub const fn public_status(self) -> synos_status::Status {
        match self {
            Self::Ok => synos_status::Status::NORMAL,
            Self::InvalidRequest => synos_status::Status::INVALID_ARGUMENT,
            Self::Unauthenticated => synos_status::Status::ACCESS_DENIED,
            Self::AccessDenied => synos_status::Status::ACCESS_DENIED,
            Self::NotFound => synos_status::Status::NOT_FOUND,
            Self::Busy => synos_status::Status::BUSY,
            Self::Capacity => synos_status::Status::NO_SPACE,
            Self::Internal => synos_status::Status::INTERNAL,
            Self::ProtocolMismatch => synos_status::Status::PROTOCOL_MISMATCH,
            Self::InvalidFrame => synos_status::Status::INVALID_ARGUMENT,
            Self::SchemaMismatch => synos_status::Status::PROTOCOL_MISMATCH,
        }
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct RpcFrameHeader {
    pub method: RpcMethod,
    pub flags: u16,
    pub request_id: u64,
    pub payload_bytes: u32,
    pub status: RpcStatus,
}

impl RpcFrameHeader {
    pub fn encode(self, output: &mut [u8]) -> Result<(), FrameError> {
        if output.len() < RPC_FRAME_HEADER_BYTES
            || self.flags & !RPC_KNOWN_FLAGS != 0
            || self.payload_bytes as usize > RPC_MAX_FRAME_BYTES - RPC_FRAME_HEADER_BYTES
        {
            return Err(FrameError::InvalidLength)
        }
        output[..RPC_FRAME_HEADER_BYTES].fill(0);
        output[0..4].copy_from_slice(&RPC_MAGIC);
        output[4] = RPC_PROTOCOL_VERSION;
        output[5] = self.method as u8;
        output[6..8].copy_from_slice(&self.flags.to_be_bytes());
        output[8..16].copy_from_slice(&self.request_id.to_be_bytes());
        output[16..20].copy_from_slice(&self.payload_bytes.to_be_bytes());
        output[20..22].copy_from_slice(&(self.status as u16).to_be_bytes());
        Ok(())
    }

    pub fn decode(input: &[u8]) -> Result<Self, FrameError> {
        if input.len() < RPC_FRAME_HEADER_BYTES {
            return Err(FrameError::BufferTooSmall)
        }
        if input[0..4] != RPC_MAGIC {
            return Err(FrameError::InvalidMagic)
        }
        if input[4] != RPC_PROTOCOL_VERSION {
            return Err(FrameError::UnsupportedVersion)
        }
        let flags = u16::from_be_bytes([input[6], input[7]]);
        let payload_bytes = u32::from_be_bytes([input[16], input[17], input[18], input[19]]);
        if flags & !RPC_KNOWN_FLAGS != 0 {
            return Err(FrameError::InvalidFlags)
        }
        if payload_bytes as usize > RPC_MAX_FRAME_BYTES - RPC_FRAME_HEADER_BYTES
            || input.len() < RPC_FRAME_HEADER_BYTES + payload_bytes as usize
        {
            return Err(FrameError::InvalidLength)
        }
        Ok(Self {
            method: RpcMethod::from_wire(input[5])?,
            flags,
            request_id: u64::from_be_bytes(input[8..16].try_into().map_err(|_| FrameError::BufferTooSmall)?),
            payload_bytes,
            status: RpcStatus::from_wire(u16::from_be_bytes([input[20], input[21]]))?,
        })
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum FrameError {
    BufferTooSmall,
    InvalidFlags,
    InvalidFrame,
    InvalidLength,
    InvalidMagic,
    InvalidStatus,
    SchemaMismatch,
    UnknownMethod,
    UnsupportedVersion,
}
