[package]
name = "ghostos-ras"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[lib]
path = "src/lib.rs"

[dependencies]
ghostos-fabric = { path = "../fabric" }
ghostos-legacy-pc-drivers = { path = "../legacy-pc-drivers" }
ghostos-observability = { path = "../observability" }
ghostos-status = { path = "../status" }
ghostos-ghostfs = { path = "../ghostfs" }
