// DO NOT EDIT. Generated by tools/generate_abi.py from abi/synos-abi.toml.
import Foundation

enum SynOSABI {
    static let apiVersion: UInt16 = 1
    static let schemaVersion: UInt16 = 1
    static let revision: UInt16 = 2
    static let protocolVersion: UInt8 = 1
    static let magic = Data([83, 89, 82, 80])
    static let frameHeaderBytes = 24
    static let maxFrameBytes = 4096
    static let capabilityFlag: UInt16 = 1
}

enum SynOSRPCMethod: UInt8 {
    case clusterState = 1
    case submitJob = 2
    case delegateCapability = 3
    case topologyState = 4
    case clusterSummary = 5
    case clusterMembers = 6
    case clusterInvitations = 7
    case clusterJoinPlan = 8
    case clusterLeavePlan = 9
    case clusterHealth = 10
    case clusterResources = 11
    case clusterAudit = 12
    case clusterCreate = 13
    case clusterJoin = 14
    case clusterLeave = 15
    case clusterRemove = 16
    case subscribe = 17
    case poll = 18
}

enum SynOSRPCStatus: UInt16 {
    case ok = 0
    case invalidRequest = 1
    case unauthenticated = 2
    case accessDenied = 3
    case notFound = 4
    case busy = 5
    case capacity = 6
    case internalError = 7
    case protocolMismatch = 8
    case invalidFrame = 9
    case schemaMismatch = 10
}
