#!/usr/bin/env python3
"""Generate the workspace API documentation index used by the cookbook."""

from __future__ import annotations

import json
import subprocess
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
OUTPUT = ROOT / "docs" / "api.md"


def metadata() -> dict:
    result = subprocess.run(
        ["cargo", "metadata", "--no-deps", "--format-version", "1"],
        cwd=ROOT,
        check=True,
        capture_output=True,
        text=True,
    )
    return json.loads(result.stdout)


def main() -> None:
    workspace = Path(metadata()["workspace_root"])
    packages = []
    for package in metadata()["packages"]:
        if package["source"] is not None:
            continue
        libraries = [target for target in package["targets"] if "lib" in target["kind"]]
        if not libraries:
            continue
        target = libraries[0]
        manifest = Path(package["manifest_path"]).relative_to(workspace).as_posix()
        source = Path(manifest).parent / "src" / "lib.rs"
        packages.append((package["name"], target["name"], source.as_posix()))

    packages.sort()
    lines = [
        "# GhostOS API reference",
        "",
        "<!-- Generated by scripts/generate-api-docs.py. Do not edit by hand. -->",
        "",
        "Generate the public rustdoc site with:",
        "",
        "```sh",
        "cargo doc --workspace --no-deps",
        "```",
        "",
        "The HTML site is written to `target/doc`. The table below is generated",
        "from Cargo metadata and points each entry at its public crate root.",
        "",
        "| Package | Rustdoc target | Public crate root |",
        "| --- | --- | --- |",
    ]
    for package, target, source in packages:
        lines.append(f"| `{package}` | `{target}` | [`src/lib.rs`](../{source}) |")
    lines.extend(
        [
            "",
            "Cookbook coverage:",
            "",
            "- boot: `ghostos-boot-protocol`",
            "- storage: `ghostos-durability`",
            "- networking: `ghostos-netd`",
            "- capabilities: `ghostos-auth`",
            "- clusters: `ghostos-fabric`",
            "- compiler jobs: `ghostos-rustd`",
            "- recovery: `ghostos-backup`",
            "",
        ]
    )
    OUTPUT.write_text("\n".join(lines))


if __name__ == "__main__":
    main()
