[package]
name = "ghostos-fsd"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[lib]
path = "src/lib.rs"

[dependencies]
host-filesystems = { package = "ghostos-host-filesystems", path = "../host-filesystems" }
ghostos-ipc = { path = "../ipc" }
ghostos-observability = { path = "../observability" }
ghostos-path-pattern = { path = "../path-pattern" }
ghostos-status = { path = "../status" }
ghostos-ghostfs = { path = "../ghostfs" }
