#!/usr/bin/env python3
"""Generate the checked-in Rust, Swift, and C GhostOS ABI bindings."""

from __future__ import annotations

import argparse
import difflib
import pathlib
import tomllib

from generate_c_abi import generate as generate_c


ROOT = pathlib.Path(__file__).resolve().parents[1]
SCHEMA = ROOT / "abi" / "ghostos-abi.toml"
RUST_OUTPUT = ROOT / "crates" / "abi" / "src" / "generated.rs"
SWIFT_OUTPUT = ROOT / "clients" / "apple" / "Sources" / "GhostOSClient" / "GeneratedABI.swift"


def rust_match(items: list[dict], success: str, result: str) -> str:
    return "\n".join(
        f"            {item['value']} => {success}(Self::{item['name']}),"
        for item in items
    ) + f"\n            _ => {result},"


def generate_rust(schema: dict) -> str:
    abi = schema["abi"]
    operations = schema["operations"]
    methods = schema["methods"]
    statuses = schema["statuses"]
    magic = ", ".join(str(value) for value in abi["rpc_magic"].encode("ascii"))
    operation_variants = "\n".join(
        f"    {item['name']} = {item['value']}," for item in operations
    )
    operation_match = rust_match(operations, "Some", "None")
    method_variants = "\n".join(
        f"    {item['name']} = {item['value']}," for item in methods
    )
    method_match = rust_match(methods, "Ok", "Err(FrameError::UnknownMethod)")
    status_variants = "\n".join(
        f"    {item['name']} = {item['value']}," for item in statuses
    )
    status_match = rust_match(statuses, "Ok", "Err(FrameError::InvalidStatus)")
    status_public = "\n".join(
        f"            Self::{item['name']} => ghostos_status::Status::{item['public_status']},"
        for item in statuses
    )
    return f'''// DO NOT EDIT. Generated by tools/generate_abi.py from abi/ghostos-abi.toml.

pub const ABI_SCHEMA_VERSION: u16 = {abi["schema_version"]};
pub const ABI_REVISION: u16 = {abi["revision"]};
pub const RPC_PROTOCOL_VERSION: u8 = {abi["rpc_protocol_version"]};
pub const RPC_MAGIC: [u8; 4] = [{magic}];
pub const RPC_FRAME_HEADER_BYTES: usize = {abi["rpc_frame_header_bytes"]};
pub const RPC_MAX_FRAME_BYTES: usize = {abi["rpc_max_frame_bytes"]};
pub const RPC_CAPABILITY_FLAG: u16 = {abi["rpc_capability_flag"]};
pub const RPC_KNOWN_FLAGS: u16 = RPC_CAPABILITY_FLAG;

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
#[repr(u16)]
pub enum Operation {{
{operation_variants}
}}

impl Operation {{
    pub const fn from_raw(raw: u16) -> Option<Self> {{
        match raw {{
{operation_match}
        }}
    }}
}}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
#[repr(transparent)]
pub struct Capability(u64);

impl Capability {{
    pub const fn from_raw(raw: u64) -> Option<Self> {{
        if raw >> 32 == 0 {{ None }} else {{ Some(Self(raw)) }}
    }}

    pub const fn raw(self) -> u64 {{ self.0 }}
}}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
#[repr(C)]
pub struct Request {{
    pub operation: u16,
    pub abi_version: u16,
    pub flags: u16,
    pub reserved: u16,
    pub capability: u64,
    pub arguments: [u64; 6],
}}

impl Request {{
    pub const fn new(operation: Operation) -> Self {{
        Self {{
            operation: operation as u16,
            abi_version: ABI_SCHEMA_VERSION,
            flags: 0,
            reserved: 0,
            capability: 0,
            arguments: [0; 6],
        }}
    }}

    pub const fn with_capability(mut self, capability: Capability) -> Self {{
        self.capability = capability.raw();
        self
    }}

    pub const fn with_buffer(mut self, buffer: ghostos_ipc::SharedBuffer) -> Self {{
        self.arguments[0] = buffer.region.raw() as u64;
        self.arguments[1] = buffer.offset as u64;
        self.arguments[2] = buffer.length as u64;
        self.arguments[3] = buffer.writable as u64;
        self
    }}
}}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
#[repr(C)]
pub struct Response {{
    pub status: u32,
    pub flags: u32,
    pub values: [u64; 4],
}}

impl Response {{
    pub const EMPTY: Self = Self {{ status: 0, flags: 0, values: [0; 4] }};
}}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
#[repr(u8)]
pub enum RpcMethod {{
{method_variants}
}}

impl RpcMethod {{
    pub const fn from_wire(raw: u8) -> Result<Self, FrameError> {{
        match raw {{
{method_match}
        }}
    }}
}}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
#[repr(u16)]
pub enum RpcStatus {{
{status_variants}
}}

impl RpcStatus {{
    pub const fn from_wire(raw: u16) -> Result<Self, FrameError> {{
        match raw {{
{status_match}
        }}
    }}

    pub const fn public_status(self) -> ghostos_status::Status {{
        match self {{
{status_public}
        }}
    }}
}}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct RpcFrameHeader {{
    pub method: RpcMethod,
    pub flags: u16,
    pub request_id: u64,
    pub payload_bytes: u32,
    pub status: RpcStatus,
}}

impl RpcFrameHeader {{
    pub fn encode(self, output: &mut [u8]) -> Result<(), FrameError> {{
        if output.len() < RPC_FRAME_HEADER_BYTES
            || self.flags & !RPC_KNOWN_FLAGS != 0
            || self.payload_bytes as usize > RPC_MAX_FRAME_BYTES - RPC_FRAME_HEADER_BYTES
        {{
            return Err(FrameError::InvalidLength)
        }}
        output[..RPC_FRAME_HEADER_BYTES].fill(0);
        output[0..4].copy_from_slice(&RPC_MAGIC);
        output[4] = RPC_PROTOCOL_VERSION;
        output[5] = self.method as u8;
        output[6..8].copy_from_slice(&self.flags.to_be_bytes());
        output[8..16].copy_from_slice(&self.request_id.to_be_bytes());
        output[16..20].copy_from_slice(&self.payload_bytes.to_be_bytes());
        output[20..22].copy_from_slice(&(self.status as u16).to_be_bytes());
        Ok(())
    }}

    pub fn decode(input: &[u8]) -> Result<Self, FrameError> {{
        if input.len() < RPC_FRAME_HEADER_BYTES {{
            return Err(FrameError::BufferTooSmall)
        }}
        if input[0..4] != RPC_MAGIC {{
            return Err(FrameError::InvalidMagic)
        }}
        if input[4] != RPC_PROTOCOL_VERSION {{
            return Err(FrameError::UnsupportedVersion)
        }}
        let flags = u16::from_be_bytes([input[6], input[7]]);
        let payload_bytes = u32::from_be_bytes([input[16], input[17], input[18], input[19]]);
        if flags & !RPC_KNOWN_FLAGS != 0 {{
            return Err(FrameError::InvalidFlags)
        }}
        if payload_bytes as usize > RPC_MAX_FRAME_BYTES - RPC_FRAME_HEADER_BYTES
            || input.len() < RPC_FRAME_HEADER_BYTES + payload_bytes as usize
        {{
            return Err(FrameError::InvalidLength)
        }}
        Ok(Self {{
            method: RpcMethod::from_wire(input[5])?,
            flags,
            request_id: u64::from_be_bytes(input[8..16].try_into().map_err(|_| FrameError::BufferTooSmall)?),
            payload_bytes,
            status: RpcStatus::from_wire(u16::from_be_bytes([input[20], input[21]]))?,
        }})
    }}
}}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum FrameError {{
    BufferTooSmall,
    InvalidFlags,
    InvalidFrame,
    InvalidLength,
    InvalidMagic,
    InvalidStatus,
    SchemaMismatch,
    UnknownMethod,
    UnsupportedVersion,
}}
'''


def generate_swift(schema: dict) -> str:
    abi = schema["abi"]
    magic = ", ".join(str(value) for value in abi["rpc_magic"].encode("ascii"))
    methods = "\n".join(
        f"    case {item['swift_name']} = {item['value']}" for item in schema["methods"]
    )
    statuses = "\n".join(
        f"    case {item['swift_name']} = {item['value']}" for item in schema["statuses"]
    )
    return f'''// DO NOT EDIT. Generated by tools/generate_abi.py from abi/ghostos-abi.toml.
import Foundation

enum GhostOSABI {{
    static let apiVersion: UInt16 = {abi["schema_version"]}
    static let schemaVersion: UInt16 = {abi["schema_version"]}
    static let revision: UInt16 = {abi["revision"]}
    static let protocolVersion: UInt8 = {abi["rpc_protocol_version"]}
    static let magic = Data([{magic}])
    static let frameHeaderBytes = {abi["rpc_frame_header_bytes"]}
    static let maxFrameBytes = {abi["rpc_max_frame_bytes"]}
    static let capabilityFlag: UInt16 = {abi["rpc_capability_flag"]}
}}

enum GhostOSRPCMethod: UInt8 {{
{methods}
}}

enum GhostOSRPCStatus: UInt16 {{
{statuses}
}}
'''


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    schema = tomllib.loads(SCHEMA.read_text())
    outputs = {RUST_OUTPUT: generate_rust(schema), SWIFT_OUTPUT: generate_swift(schema)}
    outputs.update(generate_c(schema))
    changed = False
    for path, content in outputs.items():
        current = path.read_text() if path.exists() else ""
        if current != content:
            changed = True
            if args.check:
                print("".join(difflib.unified_diff(
                    current.splitlines(True),
                    content.splitlines(True),
                    fromfile=str(path),
                    tofile="generated",
                )))
            else:
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(content)
    return 1 if args.check and changed else 0


if __name__ == "__main__":
    raise SystemExit(main())
