#!/usr/bin/env python3
"""Generate C ABI bindings from the shared GhostOS schema."""

from pathlib import Path
import argparse
import re
import tomllib

ROOT = Path(__file__).resolve().parents[1]


def name(value):
    return re.sub(r"(?<!^)(?=[A-Z])", "_", value).upper()


def generate(schema):
    abi = schema["abi"]
    header = '''/* Generated by tools/generate_c_abi.py. Edit abi/ghostos-abi.toml. */
#ifndef GHOSTOS_ABI_H
#define GHOSTOS_ABI_H
#include <stddef.h>
#include <stdbool.h>
#include <stdint.h>
#include "ghostos/status.h"

'''
    for key in ("schema_version", "revision", "rpc_protocol_version", "rpc_frame_header_bytes",
                "rpc_max_frame_bytes", "rpc_capability_flag"):
        prefix = "" if key.startswith("rpc_") else "ABI_"
        header += f"#define GHOSTOS_{prefix}{key.upper()} {abi[key]}u\n"
    header += "#define GHOSTOS_RPC_KNOWN_FLAGS GHOSTOS_RPC_CAPABILITY_FLAG\n"
    for group, prefix, bits in (("operations", "OP", 16), ("methods", "RPC_METHOD", 8),
                                ("statuses", "RPC_STATUS", 16)):
        header += f"\ntypedef uint{bits}_t ghostos_{prefix.lower()};\nenum {{\n"
        header += "\n".join(f"    GHOSTOS_{prefix}_{name(item['name'])} = {item['value']}," for item in schema[group])
        header += "\n};\n"
    header += '''
typedef uint64_t ghostos_capability;
typedef struct {
    uint32_t region;
    uint32_t offset;
    uint32_t length;
    bool writable;
} ghostos_shared_buffer;

typedef struct {
    uint16_t operation;
    uint16_t abi_version;
    uint16_t flags;
    uint16_t reserved;
    uint64_t capability;
    uint64_t arguments[6];
} ghostos_request;

typedef struct {
    uint32_t status;
    uint32_t flags;
    uint64_t values[4];
} ghostos_response;

_Static_assert(sizeof(ghostos_request) == 64, "request ABI size");
_Static_assert(offsetof(ghostos_request, capability) == 8, "request capability offset");
_Static_assert(offsetof(ghostos_request, arguments) == 16, "request arguments offset");
_Static_assert(sizeof(ghostos_response) == 40, "response ABI size");
_Static_assert(offsetof(ghostos_response, values) == 8, "response values offset");

/* Encode this structure explicitly; its in-memory layout is not the wire format. */
typedef struct {
    ghostos_rpc_method method;
    uint16_t flags;
    uint64_t request_id;
    uint32_t payload_bytes;
    ghostos_rpc_status status;
} ghostos_rpc_frame_header;

typedef enum {
    GHOSTOS_FRAME_OK,
    GHOSTOS_FRAME_BUFFER_TOO_SMALL,
    GHOSTOS_FRAME_INVALID_FLAGS,
    GHOSTOS_FRAME_INVALID_FRAME,
    GHOSTOS_FRAME_INVALID_LENGTH,
    GHOSTOS_FRAME_INVALID_MAGIC,
    GHOSTOS_FRAME_INVALID_STATUS,
    GHOSTOS_FRAME_SCHEMA_MISMATCH,
    GHOSTOS_FRAME_UNKNOWN_METHOD,
    GHOSTOS_FRAME_UNSUPPORTED_VERSION
} ghostos_frame_error;

extern const uint8_t ghostos_rpc_magic[4];
bool ghostos_operation_from_raw(uint16_t raw, ghostos_op *out);
bool ghostos_capability_from_raw(uint64_t raw, ghostos_capability *out);
ghostos_request ghostos_request_new(ghostos_op operation);
ghostos_request ghostos_request_with_capability(ghostos_request request, ghostos_capability capability);
ghostos_request ghostos_request_with_buffer(ghostos_request request, ghostos_shared_buffer buffer);
extern const ghostos_response ghostos_response_empty;
ghostos_frame_error ghostos_rpc_method_from_wire(uint8_t raw, ghostos_rpc_method *out);
ghostos_frame_error ghostos_rpc_status_from_wire(uint16_t raw, ghostos_rpc_status *out);
ghostos_status ghostos_rpc_public_status(ghostos_rpc_status status);
ghostos_frame_error ghostos_rpc_frame_encode(ghostos_rpc_frame_header header, uint8_t *output, size_t length);
ghostos_frame_error ghostos_rpc_frame_decode(const uint8_t *input, size_t length, ghostos_rpc_frame_header *out);
#endif
'''
    source = '''/* Generated by tools/generate_c_abi.py. Edit abi/ghostos-abi.toml. */
#include "ghostos/abi.h"

'''
    source += "const uint8_t ghostos_rpc_magic[4] = {" + ", ".join(str(x) for x in abi["rpc_magic"].encode("ascii")) + "};\n"
    source += '''const ghostos_response ghostos_response_empty = {0};

bool ghostos_capability_from_raw(uint64_t raw, ghostos_capability *out) {
    if ((raw >> 32) == 0 || out == NULL) return false;
    *out = raw;
    return true;
}

ghostos_request ghostos_request_new(ghostos_op operation) {
    ghostos_request request = {0};
    request.operation = operation;
    request.abi_version = GHOSTOS_ABI_SCHEMA_VERSION;
    return request;
}
ghostos_request ghostos_request_with_capability(ghostos_request request, ghostos_capability capability) {
    request.capability = capability;
    return request;
}
ghostos_request ghostos_request_with_buffer(ghostos_request request, ghostos_shared_buffer buffer) {
    request.arguments[0] = buffer.region;
    request.arguments[1] = buffer.offset;
    request.arguments[2] = buffer.length;
    request.arguments[3] = buffer.writable;
    return request;
}
'''
    for group, function, bits, ctype, success, failure, null_error in (
        ("operations", "ghostos_operation_from_raw", 16, "ghostos_op", "true", "false", "false"),
        ("methods", "ghostos_rpc_method_from_wire", 8, "ghostos_rpc_method", "GHOSTOS_FRAME_OK", "GHOSTOS_FRAME_UNKNOWN_METHOD", "GHOSTOS_FRAME_INVALID_FRAME"),
        ("statuses", "ghostos_rpc_status_from_wire", 16, "ghostos_rpc_status", "GHOSTOS_FRAME_OK", "GHOSTOS_FRAME_INVALID_STATUS", "GHOSTOS_FRAME_INVALID_FRAME"),
    ):
        ret = "bool" if group == "operations" else "ghostos_frame_error"
        source += f"\n{ret} {function}(uint{bits}_t raw, {ctype} *out) {{\n    if (out == NULL) return {null_error};\n    switch (raw) {{\n"
        source += "".join(f"        case {item['value']}:\n" for item in schema[group])
        source += f"            *out = raw; return {success};\n        default: return {failure};\n    }}\n}}\n"
    source += "\nghostos_status ghostos_rpc_public_status(ghostos_rpc_status status) {\n    switch (status) {\n"
    source += "".join(f"        case GHOSTOS_RPC_STATUS_{name(item['name'])}: return GHOSTOS_STATUS_{item['public_status']};\n" for item in schema["statuses"])
    source += "        default: return GHOSTOS_STATUS_INVALID_ARGUMENT;\n    }\n}\n"
    source += '''
static void write_be(uint8_t *out, uint64_t value, size_t bytes) {
    for (size_t i = 0; i < bytes; ++i) out[bytes - i - 1] = (uint8_t)(value >> (i * 8));
}
static uint64_t read_be(const uint8_t *input, size_t bytes) {
    uint64_t value = 0;
    for (size_t i = 0; i < bytes; ++i) value = (value << 8) | input[i];
    return value;
}

ghostos_frame_error ghostos_rpc_frame_encode(ghostos_rpc_frame_header header, uint8_t *output, size_t length) {
    if (output == NULL || length < GHOSTOS_RPC_FRAME_HEADER_BYTES ||
        (header.flags & ~GHOSTOS_RPC_KNOWN_FLAGS) != 0 ||
        header.payload_bytes > GHOSTOS_RPC_MAX_FRAME_BYTES - GHOSTOS_RPC_FRAME_HEADER_BYTES)
        return GHOSTOS_FRAME_INVALID_LENGTH;
    ghostos_rpc_method method;
    ghostos_rpc_status status;
    ghostos_frame_error error = ghostos_rpc_method_from_wire(header.method, &method);
    if (error != GHOSTOS_FRAME_OK) return error;
    error = ghostos_rpc_status_from_wire(header.status, &status);
    if (error != GHOSTOS_FRAME_OK) return error;
    for (size_t i = 0; i < GHOSTOS_RPC_FRAME_HEADER_BYTES; ++i) output[i] = 0;
    for (size_t i = 0; i < 4; ++i) output[i] = ghostos_rpc_magic[i];
    output[4] = GHOSTOS_RPC_PROTOCOL_VERSION;
    output[5] = header.method;
    write_be(output + 6, header.flags, 2);
    write_be(output + 8, header.request_id, 8);
    write_be(output + 16, header.payload_bytes, 4);
    write_be(output + 20, header.status, 2);
    return GHOSTOS_FRAME_OK;
}

ghostos_frame_error ghostos_rpc_frame_decode(const uint8_t *input, size_t length, ghostos_rpc_frame_header *out) {
    if (input == NULL || length < GHOSTOS_RPC_FRAME_HEADER_BYTES) return GHOSTOS_FRAME_BUFFER_TOO_SMALL;
    for (size_t i = 0; i < 4; ++i)
        if (input[i] != ghostos_rpc_magic[i]) return GHOSTOS_FRAME_INVALID_MAGIC;
    if (input[4] != GHOSTOS_RPC_PROTOCOL_VERSION) return GHOSTOS_FRAME_UNSUPPORTED_VERSION;
    ghostos_rpc_frame_header header = {0};
    header.flags = (uint16_t)read_be(input + 6, 2);
    header.payload_bytes = (uint32_t)read_be(input + 16, 4);
    if ((header.flags & ~GHOSTOS_RPC_KNOWN_FLAGS) != 0) return GHOSTOS_FRAME_INVALID_FLAGS;
    if (header.payload_bytes > GHOSTOS_RPC_MAX_FRAME_BYTES - GHOSTOS_RPC_FRAME_HEADER_BYTES ||
        length < GHOSTOS_RPC_FRAME_HEADER_BYTES + (size_t)header.payload_bytes)
        return GHOSTOS_FRAME_INVALID_LENGTH;
    ghostos_frame_error error = ghostos_rpc_method_from_wire(input[5], &header.method);
    if (error != GHOSTOS_FRAME_OK) return error;
    header.request_id = read_be(input + 8, 8);
    error = ghostos_rpc_status_from_wire((uint16_t)read_be(input + 20, 2), &header.status);
    if (error != GHOSTOS_FRAME_OK) return error;
    if (out == NULL) return GHOSTOS_FRAME_INVALID_FRAME;
    *out = header;
    return GHOSTOS_FRAME_OK;
}
'''
    return {ROOT / "c/include/ghostos/abi.h": header, ROOT / "c/src/abi.c": source}


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    schema = tomllib.loads((ROOT / "abi/ghostos-abi.toml").read_text())
    changed = False
    for path, content in generate(schema).items():
        if not path.exists() or path.read_text() != content:
            changed = True
            if args.check:
                print(f"Outdated C ABI binding: {path.relative_to(ROOT)}")
            else:
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(content)
    return int(args.check and changed)


if __name__ == "__main__":
    raise SystemExit(main())
