[package]
name = "cargo-synos"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[[bin]]
name = "cargo-synos"
path = "src/main.rs"

[dependencies]
synos-pkg = { path = "../../crates/pkg" }
synos-app = { path = "../../crates/app" }
synos-init = { path = "../../crates/init" }
synos-rustd = { path = "../../crates/synos-rustd" }
synos-runtime = { path = "../../crates/runtime" }
synos-synfs = { path = "../../crates/synfs" }
synos-system-model = { path = "../../crates/system-model" }
synos-compiler = { path = "../synos-compiler" }
synos-vm = { path = "../../virtual_machine" }
